export const API_CONFIG = {
  baseUrl: import.meta.env.VITE_API_BASE_URL,
  authUrl: import.meta.env.VITE_API_AUTH_URL,
  chatbotUrl: import.meta.env.VITE_CHATBOT_API_URL,
  endpoints: {
    getCounsellors: '/api/shared/getAllCounsellors',
    getCounsellorById: '/api/shared/getCounsellorById',
    getCounsellorNonAvailability: '/api/user/counsellorNonAvailability',
    bookAppointment: '/api/user/book',
    getExams: '/api/exams/all',
    getCourses: '/api/courses/all',
    getColleges: '/api/colleges/all',
    getQuestionsList: '/api/community/dashboard/getQuestionsList',
    getCommunityDashboard: '/api/community/dashboard/getCommunityDashboard',
    getAllAnswersForQuestion: '/api/community/dashboard/getAllAnswersForSpecificQuestion',
    askQuestion: '/api/community/questions/askQuestion',
    postAnswer: '/api/community/answers/postAnswer',
    getComments: '/api/community/dashboard/getAllCommentsOfAnAnswer',
    getReplies: '/api/community/dashboard/getAllRepliesOfAComment',
    addComment: '/api/community/answers/comments/addComment',
    addReply: '/api/community/answers/comments/replies/addReply',
    bookmarkQuestion: '/api/community/questions/bookmarkQuestion',
    bookmarkAnswer: '/api/community/answers/bookmarkAnswer',
    likeAnswer: '/api/community/answers/likeUnlikeAnswer',
    likeComment: '/api/community/answers/comments/likeComment',
    likeReply: '/api/community/answers/comments/replies/likeReply',
    getMyQuestions: '/api/community/dashboard/getMyQuestions',
    getMyAnswers: '/api/community/dashboard/getMyAnswers',
    getMyBookmarkedQuestions: '/api/community/dashboard/getMyBookmarkedQuestions',
    deleteAnswer: '/api/community/answers/deleteAnswer',
    updateAnswer: '/api/community/answers/updateAnswer',
    getAnswersByQuestionId: '/api/community/dashboard/getAnswersForMyAnswers',
  },
  defaultTimeout: 10000,
} as const;
