// AUTO-GENERATED by scripts/generate-content-snapshot.mjs — do not edit by hand.
// Build-time snapshot of the API-backed content the public pages render, so
// prerendered HTML ships real colleges/courses/tests/deadlines instead of
// empty states. The live API refreshes all of this client-side on mount.

export interface CollegeSnapshotItem {
  collegeId: string;
  collegeName: string;
  collegesLocationCity: string;
  collegesLocationState: string;
  logoUrl: string;
  establishedYear: string;
  accreditation: string;
  collegeType: string;
  popularityCount: number;
  coursesOffered: {
    courseId: string;
    courseName: string;
    courseLevel: string;
    duration: string;
    examsAccepted: { examId: string; examName: string }[];
  }[];
}

export interface CourseSnapshotItem {
  courseId: string;
  courseName: string;
  counsellorName: string;
  courseThumbnailUrl: string;
  category: string;
  rating: number;
  coursePrice: number;
  coursePriceAfterDiscount: number;
  courseTimeHours: number;
  courseTimeMinutes: number;
  soldCount: number;
  isTrending: boolean;
}

export interface TestGroupSnapshotItem {
  testGroupId: string;
  attachedTestIds: string[];
  testGroupName: string;
  testGroupDescription: string;
  bannerImagUrl: string;
  testType: string;
  priceType: string;
  price: number;
  rating: number;
  soldCount: number;
  attachedTestCount: number;
}

export interface DeadlineSnapshotItem {
  id: string;
  title: string;
  startDate: string;
  startTime: string;
  endDate: string;
  endTime: string;
  description: string;
  photoUrl: string;
  applicationUrl: string;
  typeOfEvent: string;
  priority: number;
  associatedCourseId: string[];
  associatedExamsIds: string[];
  isDeleted: boolean;
}

export const COLLEGES_SNAPSHOT: CollegeSnapshotItem[] = [
  {
    "collegeId": "VJTI_MUMBAI",
    "collegeName": "Veermata Jijabai Technological Institute",
    "collegesLocationCity": "Mumbai",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/VJTI_MUMBAI/logo/VJTI_MUMBAI_logo_20250829_125335_download.png",
    "establishedYear": "1887",
    "accreditation": "AICTE, NBA, NAAC",
    "collegeType": "Govt",
    "popularityCount": 795,
    "coursesOffered": [
      {
        "courseId": "ENGINEERING",
        "courseName": "Engineering",
        "courseLevel": "UG",
        "duration": "4 Years",
        "examsAccepted": [
          {
            "examId": "MHT_CET",
            "examName": "MHT CET"
          }
        ]
      },
      {
        "courseId": "MTECH",
        "courseName": "Mtech",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": [
          {
            "examId": "GATE",
            "examName": "GATE"
          }
        ]
      }
    ]
  },
  {
    "collegeId": "BIMM_PUNE",
    "collegeName": "Balaji Institute of Modern Management",
    "collegesLocationCity": "Pune",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/colleges/BIMM_PUNE,BIMM_PUNE/logo/logo_1755169829090.jpeg",
    "establishedYear": "1999",
    "accreditation": "NAAC, AICTE",
    "collegeType": "Pvt",
    "popularityCount": 573,
    "coursesOffered": [
      {
        "courseId": "MANAGEMENT",
        "courseName": "Management",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": [
          {
            "examId": "CAT",
            "examName": ""
          },
          {
            "examId": "MAT",
            "examName": ""
          },
          {
            "examId": "XAT",
            "examName": ""
          },
          {
            "examId": "CMAT",
            "examName": ""
          },
          {
            "examId": "ATMA",
            "examName": "ATMA"
          },
          {
            "examId": "MAH_MBA_CET",
            "examName": "MAH MBA CET"
          }
        ]
      }
    ]
  },
  {
    "collegeId": "CEP_PUNE",
    "collegeName": "College of Engineering Pune",
    "collegesLocationCity": "Pune",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/CEP_PUNE/logo/CEP_PUNE_logo_20250829_102026_coep.png",
    "establishedYear": "1854",
    "accreditation": "AICTE, NBA, NAAC, UGC",
    "collegeType": "Govt",
    "popularityCount": 558,
    "coursesOffered": [
      {
        "courseId": "ENGINEERING",
        "courseName": "Engineering",
        "courseLevel": "UG",
        "duration": "4 Years",
        "examsAccepted": [
          {
            "examId": "MHT_CET",
            "examName": "MHT CET"
          }
        ]
      },
      {
        "courseId": "MTECH",
        "courseName": "Mtech",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": []
      }
    ]
  },
  {
    "collegeId": "SJIMR_MUMBAI",
    "collegeName": "S.P. Jain Institute of Management and Research",
    "collegesLocationCity": "Mumbai",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/SJIMR_MUMBAI/logo/SJIMR_MUMBAI_logo_20250828_114954_S.P.%20Jain%20Institute%20of%20Management%20and%20Research%20logo.jpg",
    "establishedYear": "1981",
    "accreditation": "AACSB, AMBA, EQUIS",
    "collegeType": "Pvt",
    "popularityCount": 176,
    "coursesOffered": [
      {
        "courseId": "MANAGEMENT",
        "courseName": "Management",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": [
          {
            "examId": "CAT",
            "examName": "CAT"
          },
          {
            "examId": "XAT",
            "examName": "XAT"
          },
          {
            "examId": "GMAT",
            "examName": "GMAT"
          },
          {
            "examId": "NMAT",
            "examName": "NMAT"
          },
          {
            "examId": "CMAT",
            "examName": "CMAT"
          }
        ]
      }
    ]
  },
  {
    "collegeId": "VNIT_NAGPUR",
    "collegeName": "Visvesvaraya National Institute of Technology",
    "collegesLocationCity": "Nagpur",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/VNIT_NAGPUR/logo/VNIT_NAGPUR_logo_20250829_115422_VNIT_logo.jpeg",
    "establishedYear": "1960",
    "accreditation": "AICTE, UGC, NBA, NIRF",
    "collegeType": "Govt",
    "popularityCount": 135,
    "coursesOffered": [
      {
        "courseId": "ENGINEERING",
        "courseName": "Engineering",
        "courseLevel": "UG",
        "duration": "4 Years",
        "examsAccepted": [
          {
            "examId": "JEE_MAIN",
            "examName": "JEE Main"
          }
        ]
      },
      {
        "courseId": "MTECH",
        "courseName": "Mtech",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": [
          {
            "examId": "GATE",
            "examName": "GATE"
          }
        ]
      }
    ]
  },
  {
    "collegeId": "BITSSM_MUMBAI",
    "collegeName": "Birla Institute of Technology and Science School of Management",
    "collegesLocationCity": "Mumbai",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/BITSSM_MUMBAI/logo/BITSSM_MUMBAI_logo_20250830_085343_Birla%20Institute%20of%20Technology%20and%20Science%20School%20of%20Management%20logo.jpg",
    "establishedYear": "2021",
    "accreditation": "AICTE, NAAC, NBA",
    "collegeType": "Pvt",
    "popularityCount": 129,
    "coursesOffered": [
      {
        "courseId": "MANAGEMENT",
        "courseName": "Management",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": [
          {
            "examId": "GMAT",
            "examName": "GMAT"
          },
          {
            "examId": "CAT",
            "examName": "CAT"
          },
          {
            "examId": "GRE",
            "examName": "GRE"
          }
        ]
      }
    ]
  },
  {
    "collegeId": "CCEFW_PUNE",
    "collegeName": "Cummins College of Engineering for Women",
    "collegesLocationCity": "Pune",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/CCEFW_PUNE/logo/CCEFW_PUNE_logo_20250830_112714_logo.jpeg",
    "establishedYear": "1991",
    "accreditation": "NAAC (A), NBA, AICTE",
    "collegeType": "Pvt",
    "popularityCount": 85,
    "coursesOffered": [
      {
        "courseId": "ENGINEERING",
        "courseName": "Engineering",
        "courseLevel": "UG",
        "duration": "4 Years",
        "examsAccepted": [
          {
            "examId": "JEE_MAIN",
            "examName": "JEE Main"
          },
          {
            "examId": "MHT_CET",
            "examName": "MHT CET"
          }
        ]
      },
      {
        "courseId": "MTECH",
        "courseName": "Mtech",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": []
      }
    ]
  },
  {
    "collegeId": "SPIT_MUMBAI",
    "collegeName": "Sardar Patel Institute of Technology",
    "collegesLocationCity": "Mumbai",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/SPIT_MUMBAI/logo/SPIT_MUMBAI_logo_20250829_133400_images.png",
    "establishedYear": "2005",
    "accreditation": "AICTE, NAAC, NBA",
    "collegeType": "Pvt",
    "popularityCount": 79,
    "coursesOffered": [
      {
        "courseId": "ENGINEERING",
        "courseName": "Engineering",
        "courseLevel": "UG",
        "duration": "4 Years",
        "examsAccepted": [
          {
            "examId": "MHT_CET",
            "examName": "MHT CET"
          }
        ]
      },
      {
        "courseId": "MTECH",
        "courseName": "Mtech",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": [
          {
            "examId": "otherExam1",
            "examName": "GATE"
          }
        ]
      }
    ]
  },
  {
    "collegeId": "IIM_PUNE",
    "collegeName": "Indira Institute of Management",
    "collegesLocationCity": "Pune",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/IIM_PUNE/logo/IIM_PUNE_logo_20250819_090957_Indra%20Logo.jpeg",
    "establishedYear": "1994",
    "accreditation": "NA",
    "collegeType": "Pvt",
    "popularityCount": 76,
    "coursesOffered": [
      {
        "courseId": "MANAGEMENT",
        "courseName": "Master of Business Administration (MBA)",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": [
          {
            "examId": "CAT",
            "examName": "CAT"
          },
          {
            "examId": "MAT",
            "examName": "MAT"
          },
          {
            "examId": "XAT",
            "examName": "XAT"
          },
          {
            "examId": "CMAT",
            "examName": "CMAT"
          },
          {
            "examId": "ATMA",
            "examName": "ATMA"
          },
          {
            "examId": "otherExam1",
            "examName": "MAH-CET"
          }
        ]
      }
    ]
  },
  {
    "collegeId": "DJSCE_MUMBAI",
    "collegeName": "D. J. Sanghvi College of Engineering",
    "collegesLocationCity": "Mumbai",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/DJSCE_MUMBAI/logo/DJSCE_MUMBAI_logo_20250830_120708_DJSCE_Logo.png",
    "establishedYear": "1994",
    "accreditation": "NAAC (A+), NBA, AICTE",
    "collegeType": "Pvt",
    "popularityCount": 75,
    "coursesOffered": [
      {
        "courseId": "ENGINEERING",
        "courseName": "Engineering",
        "courseLevel": "UG",
        "duration": "4 Years",
        "examsAccepted": []
      }
    ]
  },
  {
    "collegeId": "RAIT_NAVI_MUMBAI",
    "collegeName": "Ramrao Adik Institute of Technology",
    "collegesLocationCity": "Navi Mumbai",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/RAIT_NAVI_MUMBAI/logo/RAIT_NAVI_MUMBAI_logo_20250830_101613_images.jpeg",
    "establishedYear": "1983",
    "accreditation": "NAAC (A), NBA, AICTE",
    "collegeType": "Pvt",
    "popularityCount": 75,
    "coursesOffered": [
      {
        "courseId": "ENGINEERING",
        "courseName": "Engineering",
        "courseLevel": "UG",
        "duration": "4 Years",
        "examsAccepted": [
          {
            "examId": "JEE_MAIN",
            "examName": "JEE Main"
          },
          {
            "examId": "MHT_CET",
            "examName": "MHT CET"
          }
        ]
      },
      {
        "courseId": "MTECH",
        "courseName": "Mtech",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": [
          {
            "examId": "GATE",
            "examName": "GATE"
          }
        ]
      }
    ]
  },
  {
    "collegeId": "SIBM_PUNE",
    "collegeName": "Symbiosis Institute of Business Management",
    "collegesLocationCity": "Pune",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/SIBM_PUNE/logo/SIBM_PUNE_logo_20250828_130758_Symbiosis%20Institute%20of%20Business%20Management%20logo.png",
    "establishedYear": "1978",
    "accreditation": "NAAC, NBA, AICTE",
    "collegeType": "Pvt",
    "popularityCount": 73,
    "coursesOffered": [
      {
        "courseId": "MANAGEMENT",
        "courseName": "Management",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": [
          {
            "examId": "SNAP",
            "examName": "SNAP"
          }
        ]
      }
    ]
  },
  {
    "collegeId": "GRCE_NAGPUR",
    "collegeName": "G.H. Raisoni College of Engineering",
    "collegesLocationCity": "Nagpur",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/GRCE_NAGPUR/logo/GRCE_NAGPUR_logo_20250830_102714_ghrce-logo-white.png",
    "establishedYear": "1996",
    "accreditation": "NBA, NAAC (A+), AICTE",
    "collegeType": "Pvt",
    "popularityCount": 71,
    "coursesOffered": [
      {
        "courseId": "ENGINEERING",
        "courseName": "Engineering",
        "courseLevel": "UG",
        "duration": "4 Years",
        "examsAccepted": [
          {
            "examId": "JEE_MAIN",
            "examName": "JEE Main"
          },
          {
            "examId": "MHT_CET",
            "examName": "MHT CET"
          }
        ]
      },
      {
        "courseId": "MTECH",
        "courseName": "Mtech",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": []
      }
    ]
  },
  {
    "collegeId": "JBIMS_MUMBAI",
    "collegeName": "Jamnalal Bajaj Institute of Management Studies",
    "collegesLocationCity": "Mumbai",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/JBIMS_MUMBAI/logo/JBIMS_MUMBAI_logo_20250828_121418_Jamnalal%20Bajaj%20Institute%20of%20Management%20Studies%20LOGO.jpg",
    "establishedYear": "1965",
    "accreditation": "AICTE, NAAC",
    "collegeType": "Govt",
    "popularityCount": 65,
    "coursesOffered": [
      {
        "courseId": "MANAGEMENT",
        "courseName": "Management",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": [
          {
            "examId": "MAHCET",
            "examName": "MAH CET"
          },
          {
            "examId": "CAT",
            "examName": "CAT"
          },
          {
            "examId": "CMAT",
            "examName": "CMAT"
          },
          {
            "examId": "GMAT",
            "examName": "GMAT"
          },
          {
            "examId": "MAT",
            "examName": "MAT"
          }
        ]
      }
    ]
  },
  {
    "collegeId": "AIT_PUNE",
    "collegeName": "Army Institute of Technology",
    "collegesLocationCity": "Pune",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/AIT_PUNE/logo/AIT_PUNE_logo_20250829_134130_army_institute_of_technology_ait_pune_logo.jpeg",
    "establishedYear": "1994",
    "accreditation": "AICTE, NAAC, NBA",
    "collegeType": "Pvt",
    "popularityCount": 58,
    "coursesOffered": [
      {
        "courseId": "ENGINEERING",
        "courseName": "Engineering",
        "courseLevel": "UG",
        "duration": "4 Years",
        "examsAccepted": [
          {
            "examId": "JEE_MAIN",
            "examName": "JEE Main"
          }
        ]
      }
    ]
  },
  {
    "collegeId": "SJMSM_MUMBAI",
    "collegeName": "Shailesh J. Mehta School of Management",
    "collegesLocationCity": "Mumbai",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/SJMSM_MUMBAI/logo/SJMSM_MUMBAI_logo_20250830_083255_Shailesh%20J.%20Mehta%20School%20of%20Management%20logo.png",
    "establishedYear": "1995",
    "accreditation": "AMBA, AACSB, NBA",
    "collegeType": "Govt",
    "popularityCount": 55,
    "coursesOffered": [
      {
        "courseId": "MANAGEMENT",
        "courseName": "Management",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": [
          {
            "examId": "CAT",
            "examName": "CAT"
          }
        ]
      }
    ]
  },
  {
    "collegeId": "MPSTME_MUMBAI",
    "collegeName": "Mukesh Patel School of Technology Management and Engineering",
    "collegesLocationCity": "Mumbai",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/MPSTME_MUMBAI/logo/MPSTME_MUMBAI_logo_20250830_122930_Narsee_Monjee_Institute_of_Management_Studies_Logo.png",
    "establishedYear": "2006",
    "accreditation": "NAAC (A+), AICTE",
    "collegeType": "Pvt",
    "popularityCount": 53,
    "coursesOffered": [
      {
        "courseId": "ENGINEERING",
        "courseName": "Engineering",
        "courseLevel": "UG",
        "duration": "4 Years",
        "examsAccepted": [
          {
            "examId": "NMIMS_NPAT",
            "examName": "NMIMS NPAT"
          },
          {
            "examId": "JEE_MAIN",
            "examName": "JEE Main"
          }
        ]
      },
      {
        "courseId": "MTECH",
        "courseName": "Mtech",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": [
          {
            "examId": "GATE",
            "examName": "GATE"
          }
        ]
      }
    ]
  },
  {
    "collegeId": "SCFMHRD_PUNE",
    "collegeName": "Symbiosis Centre for Management & Human Resource Development",
    "collegesLocationCity": "Pune",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/SCFMHRD_PUNE/logo/SCFMHRD_PUNE_logo_20250830_090408_Symbiosis%20Centre%20for%20Management%20%26%20Human%20Resource%20Development%20logo.png",
    "establishedYear": "1993",
    "accreditation": "NAAC, NBA, AICTE",
    "collegeType": "Pvt",
    "popularityCount": 49,
    "coursesOffered": [
      {
        "courseId": "MANAGEMENT",
        "courseName": "Management",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": [
          {
            "examId": "SNAP",
            "examName": "SNAP"
          }
        ]
      }
    ]
  },
  {
    "collegeId": "IIMN_MUMBAI",
    "collegeName": "Indian Institute of Management Nagpur",
    "collegesLocationCity": "Mumbai",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/IIMN_MUMBAI/logo/IIMN_MUMBAI_logo_20250828_105610_Indian%20Institute%20of%20Management%20Nagpur%20logo.png",
    "establishedYear": "1963",
    "accreditation": "NAAC, AICTE",
    "collegeType": "Govt",
    "popularityCount": 48,
    "coursesOffered": [
      {
        "courseId": "MANAGEMENT",
        "courseName": "Management",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": [
          {
            "examId": "CAT",
            "examName": "CAT"
          }
        ]
      }
    ]
  },
  {
    "collegeId": "MUICT_MUMBAI",
    "collegeName": "Institute of Chemical Technology",
    "collegesLocationCity": "Mumbai",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/MUICT_MUMBAI/logo/MUICT_MUMBAI_logo_20250829_100434_institute-of-chemical-technology-mumbai-logo.webp",
    "establishedYear": "1933",
    "accreditation": "UGC, AICTE, NBA, NAAC",
    "collegeType": "Govt",
    "popularityCount": 48,
    "coursesOffered": [
      {
        "courseId": "ENGINEERING",
        "courseName": "Engineering",
        "courseLevel": "UG",
        "duration": "4 Years",
        "examsAccepted": [
          {
            "examId": "MHT_CET",
            "examName": "MHT CET"
          },
          {
            "examId": "JEE_MAIN",
            "examName": "JEE Main"
          }
        ]
      },
      {
        "courseId": "MTECH",
        "courseName": "M.E/M.Tech",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": [
          {
            "examId": "MAHCET",
            "examName": "MAH CET"
          }
        ]
      }
    ]
  },
  {
    "collegeId": "NMIMS_MUMBAI",
    "collegeName": "Narsee Monjee Institute of Management Studies",
    "collegesLocationCity": "Navi Mumbai",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/NMIMS_MUMBAI/logo/NMIMS_MUMBAI_logo_20250828_125251_Narsee%20Monjee%20Institute%20of%20Management%20Studies%20logo.jpg",
    "establishedYear": "2017",
    "accreditation": "AICTE, NBA",
    "collegeType": "Pvt",
    "popularityCount": 48,
    "coursesOffered": [
      {
        "courseId": "MANAGEMENT",
        "courseName": "Management",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": [
          {
            "examId": "NMAT",
            "examName": "NMAT"
          }
        ]
      }
    ]
  },
  {
    "collegeId": "TISS_MUMBAI",
    "collegeName": "Tata Institute of Social Sciences",
    "collegesLocationCity": "Mumbai",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/TISS_MUMBAI/logo/TISS_MUMBAI_logo_20250828_112403_Tata%20Institute%20of%20Social%20Sciences%20logo.png",
    "establishedYear": "1936",
    "accreditation": "NAAC, UGC",
    "collegeType": "Deemed",
    "popularityCount": 48,
    "coursesOffered": [
      {
        "courseId": "MANAGEMENT",
        "courseName": "Management",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": [
          {
            "examId": "TISSNET_MBA",
            "examName": "TISS NET – MBA"
          }
        ]
      }
    ]
  },
  {
    "collegeId": "KSIMSR_MUMBAI",
    "collegeName": "K.J. Somaiya Institute of Management Studies and Research",
    "collegesLocationCity": "Mumbai",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/KSIMSR_MUMBAI/logo/KSIMSR_MUMBAI_logo_20250830_181356_K.J.%20Somaiya%20Institute%20of%20Management%20Studies%20and%20Research%20logo.png",
    "establishedYear": "1981",
    "accreditation": "NBA, NAAC, AACSB (Member), AICTE",
    "collegeType": "Pvt",
    "popularityCount": 46,
    "coursesOffered": [
      {
        "courseId": "MANAGEMENT",
        "courseName": "Management",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": [
          {
            "examId": "CAT",
            "examName": "CAT"
          },
          {
            "examId": "XAT",
            "examName": "XAT"
          },
          {
            "examId": "CMAT",
            "examName": "CMAT"
          },
          {
            "examId": "GMAT",
            "examName": "GMAT"
          },
          {
            "examId": "NMAT",
            "examName": "NMAT"
          }
        ]
      }
    ]
  },
  {
    "collegeId": "WIMDR_MUMBAI",
    "collegeName": "Welingkar Institute of Management Development & Research",
    "collegesLocationCity": "Mumbai",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/WIMDR_MUMBAI/logo/WIMDR_MUMBAI_logo_20250829_100204_Welingkar%20Institute%20of%20Management%20Development%20%26%20Research%20logo.png",
    "establishedYear": "1977",
    "accreditation": "NBA, NAAC, AACSB (Membership), AICTE",
    "collegeType": "Pvt",
    "popularityCount": 45,
    "coursesOffered": [
      {
        "courseId": "MANAGEMENT",
        "courseName": "Management",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": [
          {
            "examId": "CAT",
            "examName": "CAT"
          },
          {
            "examId": "XAT",
            "examName": "XAT"
          },
          {
            "examId": "CMAT",
            "examName": "CMAT"
          },
          {
            "examId": "ATMA",
            "examName": "ATMA"
          },
          {
            "examId": "GMAT",
            "examName": "GMAT"
          },
          {
            "examId": "MHT_CET",
            "examName": "MHT CET"
          }
        ]
      }
    ]
  },
  {
    "collegeId": "ISBM_PUNE",
    "collegeName": "International School of Business & Media",
    "collegesLocationCity": "Pune",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/ISBM_PUNE/logo/ISBM_PUNE_logo_20250831_065508_International%20School%20of%20Business%20%26%20Media%20logo.jpg",
    "establishedYear": "2000",
    "accreditation": "AICTE",
    "collegeType": "Pvt",
    "popularityCount": 42,
    "coursesOffered": [
      {
        "courseId": "MANAGEMENT",
        "courseName": "MBA",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": [
          {
            "examId": "CAT",
            "examName": "CAT"
          },
          {
            "examId": "XAT",
            "examName": "XAT"
          },
          {
            "examId": "CMAT",
            "examName": "CMAT"
          },
          {
            "examId": "MAT",
            "examName": "MAT"
          },
          {
            "examId": "ATMA",
            "examName": "ATMA"
          },
          {
            "examId": "GMAT",
            "examName": "GMAT"
          }
        ]
      }
    ]
  },
  {
    "collegeId": "DMS_PUNE",
    "collegeName": "Department of Management Sciences (PUMBA)",
    "collegesLocationCity": "Pune",
    "collegesLocationState": "Maharashtra",
    "logoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/college/DMS_PUNE/logo/DMS_PUNE_logo_20250831_081008_Department%20of%20Management%20Sciences%20%28PUMBA%29%20LOGO.jpg",
    "establishedYear": "1971",
    "accreditation": "AICTE, NAAC, UGC, NBA",
    "collegeType": "Govt",
    "popularityCount": 36,
    "coursesOffered": [
      {
        "courseId": "MANAGEMENT",
        "courseName": "MBA",
        "courseLevel": "PG",
        "duration": "2 Years",
        "examsAccepted": [
          {
            "examId": "MAH_MBA_CET",
            "examName": "MAH MBA CET"
          },
          {
            "examId": "CAT",
            "examName": "CAT"
          },
          {
            "examId": "CMAT",
            "examName": "CMAT"
          }
        ]
      }
    ]
  }
];

export const COURSES_SNAPSHOT: CourseSnapshotItem[] = [
  {
    "courseId": "56d0e32c-1182-4d42-b1c3-f52693843684",
    "courseName": "HSC Titan Batch",
    "counsellorName": "",
    "courseThumbnailUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/CounsellorCourses/9322092791/56d0e32c-1182-4d42-b1c3-f52693843684/thumbnail_1778513912282.jpg",
    "category": "COURSE",
    "rating": 0,
    "coursePrice": 299,
    "coursePriceAfterDiscount": 249,
    "courseTimeHours": 0,
    "courseTimeMinutes": 0,
    "soldCount": 1,
    "isTrending": false
  },
  {
    "courseId": "819a170c-f623-4be3-b4fc-dbd42c826d36",
    "courseName": "Abc",
    "counsellorName": "",
    "courseThumbnailUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/CounsellorCourses/0000000091/819a170c-f623-4be3-b4fc-dbd42c826d36/thumbnail_1778516208422.jpg",
    "category": "COURSE",
    "rating": 0,
    "coursePrice": 1,
    "coursePriceAfterDiscount": 1,
    "courseTimeHours": 0,
    "courseTimeMinutes": 0,
    "soldCount": 1,
    "isTrending": false
  },
  {
    "courseId": "2a385b01-3275-41be-ac34-d3a10bed49a3",
    "courseName": "MPSC / UPSC / BANKING",
    "counsellorName": "",
    "courseThumbnailUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/CounsellorCourses/9970650363/2a385b01-3275-41be-ac34-d3a10bed49a3/thumbnail_1771340867451.jpg",
    "category": "COURSE",
    "rating": 0,
    "coursePrice": 5000,
    "coursePriceAfterDiscount": 3000,
    "courseTimeHours": 0,
    "courseTimeMinutes": 0,
    "soldCount": 0,
    "isTrending": false
  },
  {
    "courseId": "3ab3bdcd-0a6b-4cd1-9320-64633d8ab20b",
    "courseName": "Communication Skill, Assertive Behaviour and Trasactional Analysis",
    "counsellorName": "",
    "courseThumbnailUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/CounsellorCourses/9987564702/3ab3bdcd-0a6b-4cd1-9320-64633d8ab20b/thumbnail_1771758702874.jpg",
    "category": "COURSE",
    "rating": 0,
    "coursePrice": 1500,
    "coursePriceAfterDiscount": 1200,
    "courseTimeHours": 0,
    "courseTimeMinutes": 0,
    "soldCount": 0,
    "isTrending": false
  },
  {
    "courseId": "8d8adc1a-9eff-41f6-bc27-5f7845e09c66",
    "courseName": "Psychometric/ DMIT test for All aged Gp",
    "counsellorName": "",
    "courseThumbnailUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/CounsellorCourses/9987564702/8d8adc1a-9eff-41f6-bc27-5f7845e09c66/thumbnail_1770784044276.jpg",
    "category": "COURSE",
    "rating": 0,
    "coursePrice": 75000,
    "coursePriceAfterDiscount": 65000,
    "courseTimeHours": 0,
    "courseTimeMinutes": 0,
    "soldCount": 0,
    "isTrending": false
  },
  {
    "courseId": "a0f88d0d-e189-4ba6-8f64-f4bd5dc39108",
    "courseName": "Abc",
    "counsellorName": "",
    "courseThumbnailUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/CounsellorCourses/0000000091/a0f88d0d-e189-4ba6-8f64-f4bd5dc39108/thumbnail_1778517587384.jpg",
    "category": "COURSE",
    "rating": 0,
    "coursePrice": 1,
    "coursePriceAfterDiscount": 1,
    "courseTimeHours": 0,
    "courseTimeMinutes": 0,
    "soldCount": 0,
    "isTrending": false
  },
  {
    "courseId": "ab5afb3b-081c-4121-ac4c-8f721943d950",
    "courseName": "Career Assessment Test( DMIT/ Psychometric test",
    "counsellorName": "",
    "courseThumbnailUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/CounsellorCourses/9987564702/ab5afb3b-081c-4121-ac4c-8f721943d950/thumbnail_1771758955571.jpg",
    "category": "COURSE",
    "rating": 0,
    "coursePrice": 60000,
    "coursePriceAfterDiscount": 50000,
    "courseTimeHours": 0,
    "courseTimeMinutes": 0,
    "soldCount": 0,
    "isTrending": false
  },
  {
    "courseId": "ab721e02-21c9-4da1-af3e-7612c9081c98",
    "courseName": "Asdsa",
    "counsellorName": "",
    "courseThumbnailUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/CounsellorCourses/9470988669/ab721e02-21c9-4da1-af3e-7612c9081c98/thumbnail_1778520224836.jpg",
    "category": "COURSE",
    "rating": 0,
    "coursePrice": 100,
    "coursePriceAfterDiscount": 90,
    "courseTimeHours": 0,
    "courseTimeMinutes": 0,
    "soldCount": 0,
    "isTrending": false
  },
  {
    "courseId": "b1b74f9c-7f68-4240-ab50-2b6d483baf3a",
    "courseName": "Music Class",
    "counsellorName": "",
    "courseThumbnailUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/CounsellorCourses/9987564702/b1b74f9c-7f68-4240-ab50-2b6d483baf3a/thumbnail_1770785296179.jpg",
    "category": "COURSE",
    "rating": 0,
    "coursePrice": 12000,
    "coursePriceAfterDiscount": 11000,
    "courseTimeHours": 0,
    "courseTimeMinutes": 0,
    "soldCount": 0,
    "isTrending": false
  },
  {
    "courseId": "b801e862-fbfb-41b7-9864-779f77c70d08",
    "courseName": "IIT Foundation Physics",
    "counsellorName": "",
    "courseThumbnailUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/CounsellorCourses/9470988669/b801e862-fbfb-41b7-9864-779f77c70d08/thumbnail_1763658447530.jpg",
    "category": "PYQ",
    "rating": 0,
    "coursePrice": 2500,
    "coursePriceAfterDiscount": 2000,
    "courseTimeHours": 0,
    "courseTimeMinutes": 0,
    "soldCount": 0,
    "isTrending": false
  }
];

export const TEST_GROUPS_SNAPSHOT: TestGroupSnapshotItem[] = [
  {
    "testGroupId": "de8eedeb-3db0-4280-b872-9563b7f88d7f",
    "attachedTestIds": [
      "Kwfy45FjHmcdo7ScGxMr",
      "DGf0cRpuUQw4ljtemUPC"
    ],
    "testGroupName": "Grand Mock Test By Aaditya Coep | 29th March",
    "testGroupDescription": "Date: 29th March\nTime: 2â5 PM\n\nTarget: 3000+ Students\n\nExperience the real MHT-CET exam environment before your actual attempt!\nBoost your speed, accuracy & confidence with MAHARASHTRAâs most realistic mock test.\n\nâ Full-Length Exam (PCM Pattern)\nâ Same Interface as Actual CET\nâ Detailed Analysis & Rank Prediction\nâ ALL MAHARASHTRA RANKING\n\nLIVE PAPER SOLVING WILL BE PROVIDED IF AND ONLY IF WE CROSS 3,000/- ENROLLMENTS FOR THE TEST!",
    "bannerImagUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/TestGroups/de8eedeb-3db0-4280-b872-9563b7f88d7f/banner_1774298124574.jpg",
    "testType": "STANDALONE",
    "priceType": "FREE",
    "price": 0,
    "rating": 4.726027397260274,
    "soldCount": 455,
    "attachedTestCount": 1
  },
  {
    "testGroupId": "d092274f-842b-4859-b728-18db82658059",
    "attachedTestIds": [
      "0OwjU7353uHl3m9xQbGI",
      "ZzVSUGXHOd1SxWHSGkxB",
      "udmPuYug0XNVPTcr9SZh",
      "XNPsgkNrtQfZkwmuAWO4",
      "Y5mwCm1B3XauLoOMWN1X",
      "Psq5tDJr2HMVmRQu1bjH",
      "cFUPyfH07nEEuvKzx6vq",
      "zQiFb7sdJKyrdywhLva5",
      "gZqPfMemM8EYV4IMaebK",
      "DkRdb2C28dpXZJ2KdWGM"
    ],
    "testGroupName": "Kurukshetra Mock Test 4.0 Lite",
    "testGroupDescription": "10 Full Length Mock Tests with Video Solutions",
    "bannerImagUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/TestGroups/d092274f-842b-4859-b728-18db82658059/banner_1774250376036.jpg",
    "testType": "STANDALONE",
    "priceType": "PAID",
    "price": 599,
    "rating": 0,
    "soldCount": 16,
    "attachedTestCount": 10
  },
  {
    "testGroupId": "8334ebc6-8de7-416c-b4fb-9bace6545d33",
    "attachedTestIds": [
      "0OwjU7353uHl3m9xQbGI"
    ],
    "testGroupName": "Kurukshetra Mock Test 4.0 Demo",
    "testGroupDescription": "Maharashtra Best Test Series Made by Students from Top Colleges",
    "bannerImagUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/TestGroups/8334ebc6-8de7-416c-b4fb-9bace6545d33/banner_1773947279309.jpg",
    "testType": "STANDALONE",
    "priceType": "PAID",
    "price": 48,
    "rating": 0,
    "soldCount": 0,
    "attachedTestCount": 1
  },
  {
    "testGroupId": "22fa5977-2e64-417a-821b-2cd09b862b7d",
    "attachedTestIds": [
      "avEiSiHvD5WnINc9uSBZ",
      "kDAaUPyWRdpy2qxcjqd0",
      "4oCrnj2MEl5sIZRbFXAD",
      "WpBetURjuU2347rB9KuK",
      "Ml9Q8QH9BwQM6VkGpJ5b",
      "D7A4moS9JoDYlWgl8Hm6",
      "Le3jsxaTWN9Ey3YWC2qL",
      "DFYb3t65AvGHb6jsgI0p",
      "U3XpE9XjsEr79pi6cfqp",
      "bLsd0OIiSSF1RfQeWNDM",
      "xFk1FiSxYvYfIu8nVDmI",
      "vQbvr7CamV6eU5iMTfrG",
      "4rtjtU3rVbt0HoiR82it",
      "b8CO7ytuLUjiK9E0oLsZ",
      "kUp5AWpOBKJW3btdoUaK",
      "Zenw9nqasb5fgcXteqFo",
      "Ko9DhQFR482utTyWPghl",
      "hnj8tqFZtKYP5v6gmYEt",
      "UaKysDLr6E1SSE08PMDF",
      "kOoHsGbtviFcHV33PzwH",
      "c9LiJh6At6Xd0wTRTZvE",
      "dRz3ZTfNKFf0jPrFH2QN",
      "09rykUDNra7kMyWqdF4i"
    ],
    "testGroupName": "Mathematics - Chapterwise",
    "testGroupDescription": "Mathematics - Chapterwise",
    "bannerImagUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/TestGroups/22fa5977-2e64-417a-821b-2cd09b862b7d/banner_1772615721020.jpg",
    "testType": "STANDALONE",
    "priceType": "PAID",
    "price": 499,
    "rating": 0,
    "soldCount": 287,
    "attachedTestCount": 23
  },
  {
    "testGroupId": "2412daaf-ddf0-4fbc-b09e-41ccd2d87c1a",
    "attachedTestIds": [
      "seosjSFed7mSQWfPkYrd",
      "rs2T99hez1m4skpx0ob8",
      "2gSjRrOdWYd5xC7AU29l",
      "ZOAkLvRhODxJsOlrNV6k",
      "7jvODC7wwPVstOUBcveh",
      "HEwYkuhw3SHwNzifbzEl",
      "spOY6xmI1zl9PFjTjdSs",
      "iRYcSp2hVAr6PlyE1DEE",
      "ncdAMUWWwtg1D45xWHNs",
      "usq8SDCCXOmOyNo8uKHF",
      "naW7Zh5HwVjovS92j6Rh",
      "9S5cLkzisbMY7T2nUvo9",
      "S90uTUMbV7cyN1kXSya9",
      "6dcPjGHe8TJX1KHzCspM",
      "AvPFmRq0qzaGT1ZrSAOZ",
      "qbBABskLz1WJzme0Woja"
    ],
    "testGroupName": "Chemistry - Chapterwise",
    "testGroupDescription": "Chemistry - Chapterwise",
    "bannerImagUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/TestGroups/2412daaf-ddf0-4fbc-b09e-41ccd2d87c1a/banner_1772615679393.jpg",
    "testType": "STANDALONE",
    "priceType": "PAID",
    "price": 499,
    "rating": 0,
    "soldCount": 286,
    "attachedTestCount": 15
  },
  {
    "testGroupId": "e0e5c819-8301-4466-b064-491fc28cd754",
    "attachedTestIds": [
      "YIkUe6GJDzbEuJEpaNP6",
      "KmOQd9hjN7V3E5VZEz5u",
      "SHupG8bm26jPyIuZkvJU",
      "WQEYNUgxjX2Zh0SQ5eQm",
      "jAjhgYQ2xATs6M07kfwa",
      "PRT44vyeP4s6M6Nz4Fgj",
      "TP5zps0VSO5GLsW5iTru",
      "hg6JNQcpOYHbPyehNB2A",
      "sU6vxiVhL1slqOmg8vqm",
      "08IHuhufQPbA0P4qV2Q8",
      "0KpWDbGsSVcuZYBmSBhY",
      "Ep74luaCD2ZOCQryIlHO",
      "MFdv2D9Nt8zAMnvI22ic",
      "1llVcZoTepTuLyGHltrW",
      "figh0KDI0FU7SHcfveZY",
      "pBnqM4zKTSnfxnO87mv4",
      "gDWDwRWgnEhiphIfWyAH",
      "ixd4z96h9eYAJsYn370S",
      "J1CqUl8y7GvLh69OEesC",
      "VmHWAyh2lzOo40AUR7dS",
      "88UeYTXdSbGNBmUOGtpB",
      "9Z07QC56EwM5BlmJ5yCu",
      "2dunu5LLydzMva5OXCH0",
      "3l74HiEeX4IGrJDreuAv",
      "Fv7bbIAmkaWaC7SbYuoM",
      "GuriuHCIX4mbUIz1msmB",
      "2tlhfkZZd5NddnYVhQNg"
    ],
    "testGroupName": "Physics - Chapterwise",
    "testGroupDescription": "Physics - Chapterwise",
    "bannerImagUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/TestGroups/e0e5c819-8301-4466-b064-491fc28cd754/banner_1772615638785.jpg",
    "testType": "STANDALONE",
    "priceType": "PAID",
    "price": 499,
    "rating": 0,
    "soldCount": 288,
    "attachedTestCount": 25
  },
  {
    "testGroupId": "8a96cb41-272f-4f5a-bc61-bbc2dc669b96",
    "attachedTestIds": [
      "0OwjU7353uHl3m9xQbGI",
      "KvlCXLGQPrugockMGc8c",
      "ZzVSUGXHOd1SxWHSGkxB",
      "udmPuYug0XNVPTcr9SZh",
      "0LMF2dsTHzZzOvr3Hr3d",
      "XNPsgkNrtQfZkwmuAWO4",
      "Y5mwCm1B3XauLoOMWN1X",
      "F5HW81eH7MKasv4MwWmd",
      "Psq5tDJr2HMVmRQu1bjH",
      "cFUPyfH07nEEuvKzx6vq",
      "zQiFb7sdJKyrdywhLva5",
      "gZqPfMemM8EYV4IMaebK",
      "DkRdb2C28dpXZJ2KdWGM",
      "XCZ7hRECpMXL9574n7lT",
      "Ko7pZZfdba5aIAVbzD5Z",
      "sxqXNBliSVvsWhau7ABE",
      "MlHopchVTvf82o99lMM5",
      "AN3AllHF1clcjRKa33Q6",
      "EKepHaNVkOIqKPNzhoKK",
      "7tAlUhkMSmVdnrd2G0OB",
      "8dm2wZAZet5RFvO0v9Hu",
      "ZTwMNkOaV0tE144oAXqt",
      "HCV1MCs9ebJROyg4pdMM",
      "IZKzM7op7F6WwRsh9GvN"
    ],
    "testGroupName": "Kurukshetra Mock Test 4.0",
    "testGroupDescription": "Best Test Series for MHTCET 2026 made by students from Top Colleges.",
    "bannerImagUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/TestGroups/8a96cb41-272f-4f5a-bc61-bbc2dc669b96/banner_1772615527220.jpg",
    "testType": "STANDALONE",
    "priceType": "PAID",
    "price": 999,
    "rating": 5,
    "soldCount": 276,
    "attachedTestCount": 21
  },
  {
    "testGroupId": "6e4f3278-c3ce-4e96-9740-3ea0a6a29401",
    "attachedTestIds": [
      "zQiFb7sdJKyrdywhLva5"
    ],
    "testGroupName": "Demo Test GuruCool 2.0",
    "testGroupDescription": "This demo test gives you the idea on how the other tests are going to be, have a real experience with our latest test series",
    "bannerImagUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/TestGroups/6e4f3278-c3ce-4e96-9740-3ea0a6a29401/banner_1770458748579.jpg",
    "testType": "STANDALONE",
    "priceType": "FREE",
    "price": 0,
    "rating": 0,
    "soldCount": 186,
    "attachedTestCount": 1
  },
  {
    "testGroupId": "b648af23-2873-4b79-9af6-c6606d627f59",
    "attachedTestIds": [
      "I9IXzIoSsZw0R4VcnWyJ",
      "KvlCXLGQPrugockMGc8c",
      "W2GDG1iAH1MMndj9XvGj",
      "ZzVSUGXHOd1SxWHSGkxB",
      "bsUGIkRNG0fXWPyctW1J",
      "udmPuYug0XNVPTcr9SZh",
      "0LMF2dsTHzZzOvr3Hr3d",
      "XNPsgkNrtQfZkwmuAWO4",
      "14xUp5CudB4yG2MBK6Ss",
      "Y5mwCm1B3XauLoOMWN1X",
      "czoVrHpB8PqH7qk1V28Y",
      "4GbaozNG4krTf9KKJaNl",
      "0PM9B5uek0z1twC7BjfC",
      "ZwN8nkASuiaT974lqzNH",
      "cDDVd1zSLYtNB5XGVkn9",
      "F5HW81eH7MKasv4MwWmd",
      "Psq5tDJr2HMVmRQu1bjH",
      "P6MweHBDJuporu7XzwTG",
      "O8dxDm3wrrc2AEmRhAiG",
      "d9oojNhUrF98UY0dicUa",
      "gxRJi8iK0uuIc9vnLUfb",
      "cFUPyfH07nEEuvKzx6vq",
      "zQiFb7sdJKyrdywhLva5",
      "0OwjU7353uHl3m9xQbGI",
      "XCZ7hRECpMXL9574n7lT",
      "gZqPfMemM8EYV4IMaebK"
    ],
    "testGroupName": "Gurukool 2.0",
    "testGroupDescription": "Gurukool test series",
    "bannerImagUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/TestGroups/b648af23-2873-4b79-9af6-c6606d627f59/banner_1770535654084.jpg",
    "testType": "COURSE_ATTACHED",
    "priceType": "PAID",
    "price": 1200,
    "rating": 4.5,
    "soldCount": 178,
    "attachedTestCount": 10
  },
  {
    "testGroupId": "9b843a7e-d6dc-4d8a-8174-adf58e4cae3a",
    "attachedTestIds": [
      "KLiAFZ7wFXAevKiFxEJN",
      "PL4u9DfimCoAJqegxbfY",
      "GhOuUeOxTejBrxGEjo4a",
      "39QmljvRKtCzyyxNmaHu",
      "FkImmasjx76i22kyo5c4",
      "rfAFAkBuVuc7ruj3lIgz",
      "lO7RTNZU9UWCJ2nEFEcg",
      "bbk1ROOE9TDA4276U8la"
    ],
    "testGroupName": "HSC",
    "testGroupDescription": "This test group will include Physics, Chemistry & Mathematics Test Series.",
    "bannerImagUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/TestGroups/9b843a7e-d6dc-4d8a-8174-adf58e4cae3a/banner_1769698510262.jpg",
    "testType": "COURSE_ATTACHED",
    "priceType": "PAID",
    "price": 1,
    "rating": 5,
    "soldCount": 5,
    "attachedTestCount": 2
  }
];

export const DEADLINES_SNAPSHOT: DeadlineSnapshotItem[] = [
  {
    "id": "_iiser_aptitude_test_iat",
    "title": "IISER Aptitude Test (IAT)",
    "startDate": "2026-06-07",
    "startTime": "09:00",
    "endDate": "2026-06-07",
    "endTime": "12:00",
    "description": ".",
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/Events/_iiser_aptitude_test_iat/photo_1778168643236.jpg",
    "applicationUrl": "https://www.iiseradmission.in/",
    "typeOfEvent": "EXAM",
    "priority": 1,
    "associatedCourseId": [],
    "associatedExamsIds": [],
    "isDeleted": false
  },
  {
    "id": "aeee_2026_phase_2_examination",
    "title": "AEEE 2026 Phase 2 Examination",
    "startDate": "2026-04-24",
    "startTime": "09:00",
    "endDate": "2026-04-30",
    "endTime": "18:30",
    "description": "The AEEE (Amrita Entrance Examination â Engineering) is a computer-based online test conducted by Amrita Vishwa Vidyapeetham. The exam pattern includes multiple-choice questions (MCQs) from Physics, Chemistry, and Mathematics, with negative marking for incorrect answers. AEEE provides admission to undergraduate engineering programs offered by Amritaâs private deemed-to-be-university engineering colleges, including campuses such as Amritapuri, Coimbatore, Bengaluru, Chennai, and Amaravati.",
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/Events/aeee_2026_phase_2_examination/photo_1771337944831.jpg",
    "applicationUrl": "https://aeee.amrita.edu/",
    "typeOfEvent": "EXAM",
    "priority": 1,
    "associatedCourseId": [
      "engineering"
    ],
    "associatedExamsIds": [],
    "isDeleted": false
  },
  {
    "id": "ap_eapcet_2026_examination",
    "title": "AP EAPCET 2026 Examination",
    "startDate": "2026-05-12",
    "startTime": "09:00",
    "endDate": "2026-05-18",
    "endTime": "18:00",
    "description": "The Andhra Pradesh Engineering, Agriculture, and Pharmacy Common Entrance Test (AP EAPCET) is a 3-hour, computer-based exam held annually (typically in May) for admission into undergraduate engineering, agriculture, and pharmacy courses. Conducted by JNTUK for APSCHE, it features 160 multiple-choice questions with no negative marking.",
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/Events/ap_eapcet_2026_examination/photo_1771250089558.jpg",
    "applicationUrl": "https://cets.apsche.ap.gov.in/",
    "typeOfEvent": "EXAM",
    "priority": 1,
    "associatedCourseId": [
      "engineering"
    ],
    "associatedExamsIds": [],
    "isDeleted": false
  },
  {
    "id": "caiib__certified_associate_of_iib__f__",
    "title": "CAIIB ( Certified Associate of IIB & F )",
    "startDate": "2026-05-31",
    "startTime": "09:00",
    "endDate": "2026-06-21",
    "endTime": "12:00",
    "description": ".",
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/Events/caiib__certified_associate_of_iib__f__/photo_1777719370054.jpg",
    "applicationUrl": "https://www.iibf.org.in/CAIIB-certified-associate-IIB&F",
    "typeOfEvent": "EXAM",
    "priority": 1,
    "associatedCourseId": [],
    "associatedExamsIds": [],
    "isDeleted": false
  },
  {
    "id": "cuet_ug_2026_examination",
    "title": "CUET UG 2026 Examination",
    "startDate": "2026-05-11",
    "startTime": "09:00",
    "endDate": "2026-05-31",
    "endTime": "18:00",
    "description": "The Common University Entrance Test (CUET) is a national-level entrance exam conducted by the National Testing Agency (NTA) for admission to undergraduate (UG) and postgraduate (PG) programs at all central universities and various participating state, deemed, and private universities in India. It provides a single-window opportunity for students to apply to multiple central universities with one exam, focusing on 12th-grade NCERT-based knowledge to offer equal opportunities.",
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/Events/cuet_ug_2026_examination/photo_1771335946028.jpg",
    "applicationUrl": "https://cuet.nta.nic.in/",
    "typeOfEvent": "EXAM",
    "priority": 1,
    "associatedCourseId": [
      "engineering"
    ],
    "associatedExamsIds": [
      "CUET"
    ],
    "isDeleted": false
  },
  {
    "id": "kcet_2026_examination",
    "title": "KCET 2026 Examination",
    "startDate": "2026-04-23",
    "startTime": "10:30",
    "endDate": "2026-04-24",
    "endTime": "16:00",
    "description": "The Karnataka Common Entrance Test (KCET), commonly known as UGCET, is a state-level entrance exam for admission to undergraduate courses in engineering, pharmacy, agriculture, and other professional fields in Karnataka. Conducted by the Karnataka Examinations Authority (KEA), it is a pen-and-paper, multiple-choice question exam held in April/May for government and private colleges.",
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/Events/kcet_2026_examination/photo_1771334344509.jpg",
    "applicationUrl": "https://cetonline.karnataka.gov.in/kea/",
    "typeOfEvent": "EXAM",
    "priority": 1,
    "associatedCourseId": [
      "engineering"
    ],
    "associatedExamsIds": [
      "KCET"
    ],
    "isDeleted": false
  },
  {
    "id": "keam_2026_examination",
    "title": "KEAM 2026 Examination",
    "startDate": "2026-04-13",
    "startTime": "12:00",
    "endDate": "2026-04-25",
    "endTime": "17:00",
    "description": "KEAM (Kerala Engineering Architecture Medical) is an annual entrance exam conducted by the CEE Kerala for admission to professional degree courses (Engineering, Pharmacy, Architecture, etc.) in Kerala. For 2026, the exam is a 100% computer-based test, with Engineering/Pharmacy held by CEE, while Architecture and Medical admissions use NATA/NEET scores, respectively, alongside mandatory KEAM registration.",
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/Events/keam_2026_examination/photo_1771315584618.jpg",
    "applicationUrl": "https://cee.kerala.gov.in/",
    "typeOfEvent": "EXAM",
    "priority": 1,
    "associatedCourseId": [
      "engineering"
    ],
    "associatedExamsIds": [
      "KEAM"
    ],
    "isDeleted": false
  },
  {
    "id": "mah_mhtcet_2026_attempt_1_examination",
    "title": "MAH MHTCET 2026 Attempt 1 Examination",
    "startDate": "2026-04-11",
    "startTime": "09:00",
    "endDate": "2026-04-26",
    "endTime": "17:00",
    "description": "The MHT-CET (Maharashtra Common Entrance Test) is a state-level entrance examination conducted in online (computer-based) mode. The exam pattern is based on the Maharashtra State Board syllabus, with questions from Physics, Chemistry, and Mathematics/Biology, and it is multiple-choice (MCQ) in nature with no negative marking. MHT-CET provides admission mainly to government, government-aided, and private colleges in Maharashtra, offering undergraduate programs in Engineering, Technology, and Pharmacy.",
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/Events/mah_mhtcet_2026_attempt_1_examination/photo_1771061074171.jpg",
    "applicationUrl": "https://cetcell.mahacet.org/",
    "typeOfEvent": "EXAM",
    "priority": 1,
    "associatedCourseId": [
      "engineering"
    ],
    "associatedExamsIds": [
      "MHT_CET"
    ],
    "isDeleted": false
  },
  {
    "id": "mah_mhtcet_2026_attempt_2_examination",
    "title": "MAH MHTCET 2026 Attempt 2 Examination",
    "startDate": "2026-05-10",
    "startTime": "09:00",
    "endDate": "2026-05-17",
    "endTime": "17:00",
    "description": "The MHT-CET (Maharashtra Common Entrance Test) is a state-level entrance examination conducted in online (computer-based) mode. The exam pattern is based on the Maharashtra State Board syllabus, with questions from Physics, Chemistry, and Mathematics/Biology, and it is multiple-choice (MCQ) in nature with no negative marking. MHT-CET provides admission mainly to government, government-aided, and private colleges in Maharashtra, offering undergraduate programs in Engineering, Technology, and Pharmacy.",
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/Events/mah_mhtcet_2026_attempt_2_examination/photo_1771061262042.jpg",
    "applicationUrl": "https://cetcell.mahacet.org/",
    "typeOfEvent": "EXAM",
    "priority": 1,
    "associatedCourseId": [
      "engineering"
    ],
    "associatedExamsIds": [
      "MHT_CET"
    ],
    "isDeleted": false
  },
  {
    "id": "met_2026_phase_1_examination",
    "title": "MET 2026 Phase 1 Examination",
    "startDate": "2026-04-13",
    "startTime": "09:00",
    "endDate": "2026-04-14",
    "endTime": "16:00",
    "description": "The MET (Manipal Entrance Test) is an online computer-based examination conducted by Manipal Academy of Higher Education (MAHE). The exam pattern consists of multiple-choice questions (MCQs) from Physics, Chemistry, Mathematics, and English, with a fixed time duration and negative marking for incorrect answers. MET is used for admission to undergraduate engineering and other professional programs offered at MAHEâs constituent campuses, including Manipal, Bengaluru, and other affiliated institutions, which are primarily private deemed-to-be-university colleges.",
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/Events/met_2026_phase_1_examination/photo_1770996184931.jpg",
    "applicationUrl": "https://apply.manipal.edu/",
    "typeOfEvent": "EXAM",
    "priority": 1,
    "associatedCourseId": [
      "engineering"
    ],
    "associatedExamsIds": [
      "MET"
    ],
    "isDeleted": false
  },
  {
    "id": "nda_",
    "title": "NDA",
    "startDate": "2026-09-13",
    "startTime": "09:00",
    "endDate": "2026-09-13",
    "endTime": "12:00",
    "description": ".",
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/Events/nda_/photo_1778168329422.jpg",
    "applicationUrl": "https://upsconline.gov.in/upsc/OTRP/",
    "typeOfEvent": "EXAM",
    "priority": 1,
    "associatedCourseId": [],
    "associatedExamsIds": [],
    "isDeleted": false
  },
  {
    "id": "nest_niser__2026",
    "title": "NEST (NISER ) 2026",
    "startDate": "2026-06-06",
    "startTime": "00:00",
    "endDate": "2026-06-06",
    "endTime": "00:00",
    "description": "The National Entrance Screening Test (NEST) is a compulsory online computer-based test for admission to the five-year Integrated MSc programme offered by the National Institute of Science Education and Research (NISER) and the University of Mumbai - Department of Atomic Energy Centre for Excellence in Basic Sciences (UM-DAE CEBS). NISER and UM-DAE CEBS are autonomous institutions established by the Department of Atomic Energy (DAE), Government of India, in 2007. These institutes were started with the mandate of providing research-oriented teaching in basic sciences by faculties of practising scientists aimed at creating a national pool of human resources to lead the nation to excellence in teaching and research in basic and applied sciences.\nNEST 2026 will be conducted in around 140 cities across India.",
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/Events/nest_niser__2026/photo_1767953123239.jpg",
    "applicationUrl": "https://www.nestexam.in/",
    "typeOfEvent": "EXAM",
    "priority": 2,
    "associatedCourseId": [],
    "associatedExamsIds": [],
    "isDeleted": false
  },
  {
    "id": "srmjeee_2026_phase_1_examination",
    "title": "SRMJEEE 2026 Phase 1 Examination",
    "startDate": "2026-04-23",
    "startTime": "10:00",
    "endDate": "2026-04-28",
    "endTime": "16:30",
    "description": "The SRMJEEE (SRM Joint Engineering Entrance Examination) is an online remote-proctored exam conducted by SRM Institute of Science and Technology. The exam pattern includes multiple-choice questions (MCQs) from Physics, Chemistry, Mathematics, along with English and Aptitude, and it is generally held without negative marking. SRMJEEE provides admission to undergraduate engineering programs offered by SRMâs private deemed-to-be-university campuses, such as Kattankulathur, Ramapuram, Vadapalani, and other SRM institutions across India.",
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/Events/srmjeee_2026_phase_1_examination/photo_1770991581510.jpg",
    "applicationUrl": "https://applications.srmist.edu.in/",
    "typeOfEvent": "EXAM",
    "priority": 1,
    "associatedCourseId": [
      "engineering"
    ],
    "associatedExamsIds": [
      "SRMJEEE"
    ],
    "isDeleted": false
  },
  {
    "id": "srmjeee_2026_phase_2_examination",
    "title": "SRMJEEE 2026 Phase 2 Examination",
    "startDate": "2026-06-10",
    "startTime": "10:00",
    "endDate": "2026-06-15",
    "endTime": "16:30",
    "description": "The SRMJEEE (SRM Joint Engineering Entrance Examination) is an online remote-proctored exam conducted by SRM Institute of Science and Technology. The exam pattern includes multiple-choice questions (MCQs) from Physics, Chemistry, Mathematics, along with English and Aptitude, and it is generally held without negative marking. SRMJEEE provides admission to undergraduate engineering programs offered by SRMâs private deemed-to-be-university campuses, such as Kattankulathur, Ramapuram, Vadapalani, and other SRM institutions across India.",
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/Events/srmjeee_2026_phase_2_examination/photo_1770991917034.jpg",
    "applicationUrl": "https://applications.srmist.edu.in/",
    "typeOfEvent": "EXAM",
    "priority": 1,
    "associatedCourseId": [
      "engineering"
    ],
    "associatedExamsIds": [
      "SRMJEEE"
    ],
    "isDeleted": false
  },
  {
    "id": "srmjeee_2026_phase_2_registration",
    "title": "SRMJEEE 2026 Phase 2 Registration",
    "startDate": "2025-10-30",
    "startTime": "00:00",
    "endDate": "2026-06-04",
    "endTime": "23:59",
    "description": "The SRMJEEE (SRM Joint Engineering Entrance Examination) is an online remote-proctored exam conducted by SRM Institute of Science and Technology. The exam pattern includes multiple-choice questions (MCQs) from Physics, Chemistry, Mathematics, along with English and Aptitude, and it is generally held without negative marking. SRMJEEE provides admission to undergraduate engineering programs offered by SRMâs private deemed-to-be-university campuses, such as Kattankulathur, Ramapuram, Vadapalani, and other SRM institutions across India.",
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/Events/srmjeee_2026_phase_2_registration/photo_1770991735221.jpg",
    "applicationUrl": "https://applications.srmist.edu.in/",
    "typeOfEvent": "DEADLINE",
    "priority": 1,
    "associatedCourseId": [
      "engineering"
    ],
    "associatedExamsIds": [
      "SRMJEEE"
    ],
    "isDeleted": false
  },
  {
    "id": "srmjeee_2026_phase_3_examination",
    "title": "SRMJEEE 2026 Phase 3 Examination",
    "startDate": "2026-07-04",
    "startTime": "10:00",
    "endDate": "2026-07-05",
    "endTime": "16:30",
    "description": "The SRMJEEE (SRM Joint Engineering Entrance Examination) is an online remote-proctored exam conducted by SRM Institute of Science and Technology. The exam pattern includes multiple-choice questions (MCQs) from Physics, Chemistry, Mathematics, along with English and Aptitude, and it is generally held without negative marking. SRMJEEE provides admission to undergraduate engineering programs offered by SRMâs private deemed-to-be-university campuses, such as Kattankulathur, Ramapuram, Vadapalani, and other SRM institutions across India.",
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/Events/srmjeee_2026_phase_3_examination/photo_1770992115859.jpg",
    "applicationUrl": "https://applications.srmist.edu.in/",
    "typeOfEvent": "EXAM",
    "priority": 1,
    "associatedCourseId": [
      "engineering"
    ],
    "associatedExamsIds": [
      "SRMJEEE"
    ],
    "isDeleted": false
  },
  {
    "id": "srmjeee_2026_phase_3_registration",
    "title": "SRMJEEE 2026 Phase 3 Registration",
    "startDate": "2025-10-30",
    "startTime": "00:00",
    "endDate": "2026-06-30",
    "endTime": "23:59",
    "description": "The SRMJEEE (SRM Joint Engineering Entrance Examination) is an online remote-proctored exam conducted by SRM Institute of Science and Technology. The exam pattern includes multiple-choice questions (MCQs) from Physics, Chemistry, Mathematics, along with English and Aptitude, and it is generally held without negative marking. SRMJEEE provides admission to undergraduate engineering programs offered by SRMâs private deemed-to-be-university campuses, such as Kattankulathur, Ramapuram, Vadapalani, and other SRM institutions across India.",
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/Events/srmjeee_2026_phase_3_registration/photo_1770992031656.jpg",
    "applicationUrl": "https://applications.srmist.edu.in/",
    "typeOfEvent": "DEADLINE",
    "priority": 1,
    "associatedCourseId": [
      "engineering"
    ],
    "associatedExamsIds": [
      "SRMJEEE"
    ],
    "isDeleted": false
  },
  {
    "id": "upsc__",
    "title": "UPSC",
    "startDate": "2026-08-21",
    "startTime": "09:30",
    "endDate": "2026-08-21",
    "endTime": "11:30",
    "description": "Preliminary examination 2026",
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/Events/upsc__/photo_1777543670724.jpg",
    "applicationUrl": "https://upsc.gov.in/examinations/exam-calendar",
    "typeOfEvent": "EXAM",
    "priority": 1,
    "associatedCourseId": [],
    "associatedExamsIds": [],
    "isDeleted": false
  }
];

// Accurate test counts, resolved per group. The list endpoint's
// attachedTestIds still names deleted tests, so cards must prefer this.
export const TEST_COUNT_BY_GROUP: Record<string, number> = {
  "de8eedeb-3db0-4280-b872-9563b7f88d7f": 1,
  "d092274f-842b-4859-b728-18db82658059": 10,
  "8334ebc6-8de7-416c-b4fb-9bace6545d33": 1,
  "22fa5977-2e64-417a-821b-2cd09b862b7d": 23,
  "2412daaf-ddf0-4fbc-b09e-41ccd2d87c1a": 15,
  "e0e5c819-8301-4466-b064-491fc28cd754": 25,
  "8a96cb41-272f-4f5a-bc61-bbc2dc669b96": 21,
  "6e4f3278-c3ce-4e96-9740-3ea0a6a29401": 1,
  "b648af23-2873-4b79-9af6-c6606d627f59": 10,
  "9b843a7e-d6dc-4d8a-8174-adf58e4cae3a": 2
};

// Real counts for the /courses hero — these replaced hard-coded placeholders.
export const CONTENT_COUNTS = {
  colleges: 26,
  courses: 10,
  testGroups: 10,
  tests: 109,
  courseEnrolments: 2,
  testEnrolments: 1977,
  deadlines: 18,
} as const;
