// AUTO-GENERATED by scripts/generate-content-snapshot.mjs — do not edit by hand.
// Build-time snapshot of the API-backed content the public pages render, so
// prerendered HTML ships real colleges/courses/tests/deadlines instead of
// empty states. The live API refreshes all of this client-side on mount.

export interface CounsellorSnapshotItem {
  counsellorId: string;
  encodedId: string;
  firstName: string;
  lastName: string;
  city: string;
  states: string[];
  expertise: string[];
  languagesKnow: string[];
  experience: number;
  rating: number;
  numberOfRatings: number;
  photoUrl: string;
  organisationName: string;
  /** Length of the bio in counsellorBios.ts. The bio itself is not here. */
  bioLength: number;
  ratePerYear: number;
  plusAmount: number;
  proAmount: number;
  eliteAmount: number;
}

export const COUNSELLORS_SNAPSHOT: CounsellorSnapshotItem[] = [
  {
    "counsellorId": "9028744233",
    "encodedId": "OTAyODc0NDIzMw",
    "firstName": "Poorva",
    "lastName": "Sahu",
    "city": "Pune",
    "states": [
      "Maharashtra",
      "Karnataka",
      "Telangana"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "Medical",
      "Law",
      "Pharmacy",
      "B.Sc",
      "BBA",
      "Architecture",
      "Dental"
    ],
    "languagesKnow": [
      "Hindi",
      "English",
      "Marathi"
    ],
    "experience": 14,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9028744233/1777370323281photo.jpg",
    "organisationName": "ProCounsel",
    "ratePerYear": 50000,
    "plusAmount": 50000,
    "proAmount": 75000,
    "eliteAmount": 100000,
    "bioLength": 1093
  },
  {
    "counsellorId": "9145850392",
    "encodedId": "OTE0NTg1MDM5Mg",
    "firstName": "Abhijeet",
    "lastName": "Saxena",
    "city": "Kota",
    "states": [
      "Maharashtra",
      "Rajasthan"
    ],
    "expertise": [
      "Engineering",
      "Medical"
    ],
    "languagesKnow": [
      "English",
      "Hindi"
    ],
    "experience": 17,
    "rating": 5,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9145850392/1779960529400photo.jpg",
    "organisationName": "Notebook Education",
    "ratePerYear": 10000,
    "plusAmount": 10000,
    "proAmount": 25000,
    "eliteAmount": 99000,
    "bioLength": 66
  },
  {
    "counsellorId": "9279298887",
    "encodedId": "OTI3OTI5ODg4Nw",
    "firstName": "Amit",
    "lastName": "Narayan",
    "city": "Pune",
    "states": [
      "Maharashtra",
      "Karnataka",
      "Delhi"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "Law",
      "BBA",
      "Medical"
    ],
    "languagesKnow": [
      "Hindi",
      "English",
      "Marathi"
    ],
    "experience": 8,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9279298887/1777392313467photo.jpg",
    "organisationName": "Procouncel",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 274
  },
  {
    "counsellorId": "7004789484",
    "encodedId": "NzAwNDc4OTQ4NA",
    "firstName": "Aswini",
    "lastName": "Verma",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering",
      "Medical"
    ],
    "languagesKnow": [
      "Hindi",
      "English",
      "Marathi",
      "Telugu",
      "Tamil",
      "Kannada"
    ],
    "experience": 5,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/7004789484/1779872492098photo.jpg",
    "organisationName": "Catalyst",
    "ratePerYear": 10000,
    "plusAmount": 10000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 176
  },
  {
    "counsellorId": "7903334159",
    "encodedId": "NzkwMzMzNDE1OQ",
    "firstName": "Amit",
    "lastName": "Kumar",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "Law",
      "BCA",
      "B.Com",
      "HSC"
    ],
    "languagesKnow": [
      "Hindi",
      "English"
    ],
    "experience": 8,
    "rating": 5,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/7903334159/1761941441090photo.jpg",
    "organisationName": "Aspire Edutech Services",
    "ratePerYear": 10000,
    "plusAmount": 10000,
    "proAmount": 50000,
    "eliteAmount": 99000,
    "bioLength": 527
  },
  {
    "counsellorId": "8600308485",
    "encodedId": "ODYwMDMwODQ4NQ",
    "firstName": "Rushikesh",
    "lastName": "Kulkarni",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Medical",
      "Engineering",
      "MBA",
      "Nursing",
      "Pharmacy",
      "Dental",
      "Agriculture",
      "Diploma in Engineering",
      "Polytechnic",
      "BBA",
      "BCA"
    ],
    "languagesKnow": [
      "Marathi",
      "English",
      "Hindi"
    ],
    "experience": 11,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/8600308485/1762604346631photo.jpg",
    "organisationName": "VIBRANT CAREER GUIDANCE",
    "ratePerYear": 10000,
    "plusAmount": 10000,
    "proAmount": 25000,
    "eliteAmount": 99000,
    "bioLength": 337
  },
  {
    "counsellorId": "9158755455",
    "encodedId": "OTE1ODc1NTQ1NQ",
    "firstName": "Manjula",
    "lastName": "Subhash",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "HSC",
      "BBA",
      "B.Com",
      "B.Sc",
      "Diploma in Engineering",
      "MCA",
      "B.A.",
      "Hotel Management",
      "Agriculture",
      "Animation and Multimedia",
      "Journalism and Mass Communication",
      "M.A.",
      "Architecture",
      "Design",
      "Fashion Designing",
      "Polytechnic",
      "ITI",
      "B.Ed",
      "Social Work",
      "Psychology",
      "M.Ed"
    ],
    "languagesKnow": [
      "Hindi",
      "English"
    ],
    "experience": 25,
    "rating": 5,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9158755455/1768024454583photo.jpg",
    "organisationName": "GlobalCMOpartner",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 992
  },
  {
    "counsellorId": "9470988669",
    "encodedId": "OTQ3MDk4ODY2OQ",
    "firstName": "Ashutosh",
    "lastName": "Kumar",
    "city": "Bangalore",
    "states": [
      "Maharashtra",
      "Karnataka",
      "Delhi",
      "Tamil Nadu"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "Law",
      "Medical"
    ],
    "languagesKnow": [
      "Hindi",
      "English"
    ],
    "experience": 5,
    "rating": 4,
    "numberOfRatings": 1,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9470988669/1787559832646photo.jpg",
    "organisationName": "Aspire Consultants",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 575
  },
  {
    "counsellorId": "9967503759",
    "encodedId": "OTk2NzUwMzc1OQ",
    "firstName": "Manjitkaur",
    "lastName": "Matharu",
    "city": "Pune",
    "states": [
      "Maharashtra",
      "Delhi",
      "Andhra Pradesh",
      "Bihar",
      "Rajasthan",
      "Out of India",
      "Kerala",
      "Tamil Nadu",
      "Jharkhand",
      "Telangana",
      "Karnataka",
      "Madhya Pradesh",
      "Gujarat",
      "Uttar Pradesh",
      "Assam",
      "Chhattisgarh",
      "Goa",
      "Dadra and Nagar Haveli and Daman and Diu",
      "Himachal Pradesh",
      "West Bengal",
      "Andaman and Nicobar Islands",
      "Chandigarh",
      "Tripura",
      "Punjab",
      "Odisha",
      "Haryana",
      "Jammu and Kashmir",
      "Arunachal Pradesh",
      "Uttarakhand"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "BBA",
      "Medical",
      "Law",
      "B.Com",
      "Pharmacy",
      "B.Sc",
      "BCA",
      "Diploma in Engineering",
      "MCA",
      "Dental",
      "Nursing",
      "Hotel Management",
      "M.Com",
      "M.Sc",
      "Animation and Multimedia",
      "B.A.",
      "ITI",
      "Others",
      "Cost and Management Accounting",
      "Banking and Finance",
      "HSC",
      "Fashion Designing",
      "Journalism and Mass Communication",
      "M.A.",
      "Architecture",
      "Veterinary Sciences",
      "Aviation",
      "Chartered Accountancy",
      "B.Ed",
      "Company Secretary",
      "Design",
      "M.Ed",
      "Psychology",
      "Defense Services",
      "Social Work"
    ],
    "languagesKnow": [
      "Hindi",
      "English",
      "Marathi"
    ],
    "experience": 5,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9967503759/1763994103604photo.jpg",
    "organisationName": "Aspira360 Career Counselling Service",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 1207
  },
  {
    "counsellorId": "9226416939",
    "encodedId": "OTIyNjQxNjkzOQ",
    "firstName": "Arjun",
    "lastName": "Pachauri",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "Law",
      "BBA"
    ],
    "languagesKnow": [
      "Hindi",
      "English"
    ],
    "experience": 8,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9226416939/1762162338852photo.jpg",
    "organisationName": "Elevate Education Consultancy",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 75000,
    "bioLength": 95
  },
  {
    "counsellorId": "9307633527",
    "encodedId": "OTMwNzYzMzUyNw",
    "firstName": "Prabhat",
    "lastName": "Kaushal",
    "city": "Pune",
    "states": [
      "Maharashtra",
      "Karnataka"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "Law",
      "BBA"
    ],
    "languagesKnow": [
      "Hindi",
      "English",
      "Marathi"
    ],
    "experience": 4,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9307633527/1762504790589photo.jpg",
    "organisationName": "Elevate Educations",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 301
  },
  {
    "counsellorId": "9724933750",
    "encodedId": "OTcyNDkzMzc1MA",
    "firstName": "Samkit",
    "lastName": "Shah",
    "city": "Mumbai",
    "states": [
      "Maharashtra",
      "Delhi",
      "Out of India",
      "Gujarat",
      "Karnataka",
      "Rajasthan"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "Medical",
      "BBA",
      "Pharmacy",
      "BCA",
      "B.Sc",
      "M.Sc",
      "Polytechnic",
      "HSC",
      "MCA",
      "Diploma in Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "English"
    ],
    "experience": 5,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9724933750/1762610100040photo.jpg",
    "organisationName": "CONCEPT SIMPLIFIED",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 473
  },
  {
    "counsellorId": "0000000091",
    "encodedId": "MDAwMDAwMDA5MQ",
    "firstName": "Ananya",
    "lastName": "Verma",
    "city": "Bengaluru",
    "states": [
      "Andaman and Nicobar Islands",
      "Dadra and Nagar Haveli and Daman and Diu"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "Medical",
      "Hotel Management"
    ],
    "languagesKnow": [
      "Hindi",
      "English",
      "Marathi"
    ],
    "experience": 5,
    "rating": 5,
    "numberOfRatings": 1,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/0000000091/1760890914598photo.jpg",
    "organisationName": "Eduserv",
    "ratePerYear": 1,
    "plusAmount": 1,
    "proAmount": 20000,
    "eliteAmount": 50000,
    "bioLength": 272
  },
  {
    "counsellorId": "2200000000",
    "encodedId": "MjIwMDAwMDAwMA",
    "firstName": "Harshit",
    "lastName": "Sharma",
    "city": "Mumbai",
    "states": [
      "Maharashtra",
      "Karnataka"
    ],
    "expertise": [
      "Law",
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi"
    ],
    "experience": 3,
    "rating": 5,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/2200000000/1760893623349photo.jpg",
    "organisationName": "Catalyst Consultant",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 316
  },
  {
    "counsellorId": "6202753914",
    "encodedId": "NjIwMjc1MzkxNA",
    "firstName": "Rithika",
    "lastName": "singh",
    "city": "Bengaluru",
    "states": [
      "Karnataka",
      "Bihar",
      "Maharashtra"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "BBA",
      "Medical",
      "Dental",
      "Nursing",
      "Pharmacy",
      "B.Com",
      "B.Sc",
      "BCA",
      "Architecture",
      "Fashion Designing",
      "Hotel Management",
      "Law",
      "MCA"
    ],
    "languagesKnow": [
      "English",
      "Hindi"
    ],
    "experience": 7,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/6202753914/1762932159705photo.jpg",
    "organisationName": "Procounsel",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 422
  },
  {
    "counsellorId": "6261051061",
    "encodedId": "NjI2MTA1MTA2MQ",
    "firstName": "Mayank",
    "lastName": "Dubey",
    "city": "Pune",
    "states": [
      "Maharashtra",
      "Chhattisgarh",
      "Gujarat",
      "Andhra Pradesh",
      "Delhi",
      "Rajasthan",
      "Goa",
      "Tamil Nadu",
      "Karnataka",
      "Telangana"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "BBA",
      "Diploma in Engineering",
      "Law",
      "Banking and Finance",
      "Cost and Management Accounting",
      "HSC",
      "M.Com",
      "B.Com",
      "B.Sc",
      "Hotel Management"
    ],
    "languagesKnow": [
      "English",
      "Hindi"
    ],
    "experience": 0,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/6261051061/1766739760861photo.jpg",
    "organisationName": "Dregeup education consultancy",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 20000,
    "eliteAmount": 50000,
    "bioLength": 593
  },
  {
    "counsellorId": "7030450321",
    "encodedId": "NzAzMDQ1MDMyMQ",
    "firstName": "RAMNIK",
    "lastName": "SOURAV",
    "city": "Pune",
    "states": [
      "Maharashtra",
      "Jharkhand",
      "Karnataka",
      "Tamil Nadu",
      "Rajasthan",
      "Delhi"
    ],
    "expertise": [
      "Engineering",
      "Medical",
      "HSC",
      "MBA",
      "Pharmacy",
      "B.Sc",
      "Dental",
      "Diploma in Engineering",
      "MCA",
      "M.Sc",
      "Polytechnic",
      "ITI"
    ],
    "languagesKnow": [
      "Hindi",
      "English"
    ],
    "experience": 5,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "ASPIRE EDUTECH",
    "ratePerYear": 10000,
    "plusAmount": 10000,
    "proAmount": 25000,
    "eliteAmount": 50000,
    "bioLength": 333
  },
  {
    "counsellorId": "7038078879",
    "encodedId": "NzAzODA3ODg3OQ",
    "firstName": "Mohini",
    "lastName": "Jadhav",
    "city": "Nashik",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "M.Ed",
      "UPSC",
      "Banking and Finance"
    ],
    "languagesKnow": [
      "English",
      "Hindi",
      "Marathi"
    ],
    "experience": 0,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "Dnyaneshwari coaching",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 0
  },
  {
    "counsellorId": "7038968549",
    "encodedId": "NzAzODk2ODU0OQ",
    "firstName": "REHAN",
    "lastName": "ZIYA",
    "city": "Aurangabad",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 0,
    "rating": 0,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "S GAIKWAD CLAESS",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 803
  },
  {
    "counsellorId": "7219070001",
    "encodedId": "NzIxOTA3MDAwMQ",
    "firstName": "Sumit",
    "lastName": "Agarwal",
    "city": "Pune",
    "states": [
      "Maharashtra",
      "Karnataka",
      "Tamil Nadu",
      "Out of India",
      "Delhi"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "BBA",
      "Medical",
      "Law",
      "B.Com",
      "BCA",
      "Pharmacy",
      "B.Sc",
      "Diploma in Engineering",
      "Nursing",
      "Dental",
      "HSC",
      "MCA",
      "Hotel Management",
      "M.Com",
      "B.A.",
      "Design"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 17,
    "rating": 5,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/7219070001/1766739858099photo.jpg",
    "organisationName": "ProCounsel",
    "ratePerYear": 100000,
    "plusAmount": 0,
    "proAmount": 100000,
    "eliteAmount": 200000,
    "bioLength": 1131
  },
  {
    "counsellorId": "7249109626",
    "encodedId": "NzI0OTEwOTYyNg",
    "firstName": "Avdhoot",
    "lastName": "Kokate",
    "city": "Nashik",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Marathi",
      "Hindi",
      "English"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/7249109626/1767805835221photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 440
  },
  {
    "counsellorId": "7264063555",
    "encodedId": "NzI2NDA2MzU1NQ",
    "firstName": "MANGESH",
    "lastName": "NIKAM",
    "city": "Nashik",
    "states": [
      "Maharashtra",
      "Gujarat"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "Medical",
      "BBA",
      "BCA",
      "Pharmacy",
      "Diploma in Engineering",
      "MCA",
      "Nursing",
      "Hotel Management",
      "Dental",
      "Design",
      "Architecture",
      "Polytechnic",
      "Aviation",
      "Veterinary Sciences"
    ],
    "languagesKnow": [
      "English",
      "Marathi",
      "Hindi"
    ],
    "experience": 18,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "TP Maha Career, Nashik",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 0
  },
  {
    "counsellorId": "7276169346",
    "encodedId": "NzI3NjE2OTM0Ng",
    "firstName": "Aishwarya",
    "lastName": "Bhise",
    "city": "Mumbai",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "English",
      "Hindi",
      "Marathi"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/7276169346/1766655050667photo.jpg",
    "organisationName": "Aaditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 454
  },
  {
    "counsellorId": "7276341029",
    "encodedId": "NzI3NjM0MTAyOQ",
    "firstName": "Shreya",
    "lastName": "Raut",
    "city": "Baramati",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Marathi",
      "English"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/7276341029/1767436498085photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 677
  },
  {
    "counsellorId": "7292935303",
    "encodedId": "NzI5MjkzNTMwMw",
    "firstName": "Rishab",
    "lastName": "Rajesh",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "English"
    ],
    "experience": 1,
    "rating": 3,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/7292935303/1766739876931photo.jpg",
    "organisationName": "Pro Counsel",
    "ratePerYear": 999,
    "plusAmount": 999,
    "proAmount": 4999,
    "eliteAmount": 24999,
    "bioLength": 1491
  },
  {
    "counsellorId": "7391866727",
    "encodedId": "NzM5MTg2NjcyNw",
    "firstName": "Dr. Sandesh",
    "lastName": "Bhagat",
    "city": "Dahanu",
    "states": [
      "Maharashtra",
      "Delhi",
      "Rajasthan",
      "Bihar",
      "Gujarat",
      "Out of India",
      "Goa",
      "Punjab",
      "Dadra and Nagar Haveli and Daman and Diu"
    ],
    "expertise": [
      "HSC",
      "Medical",
      "Others",
      "Pharmacy"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 3,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "KM Institute",
    "ratePerYear": 4000,
    "plusAmount": 4000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 1479
  },
  {
    "counsellorId": "7410019075",
    "encodedId": "NzQxMDAxOTA3NQ",
    "firstName": "ASMI YOUTH CAREER ADVISOR",
    "lastName": "NA",
    "city": "Thane",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering",
      "Medical",
      "Pharmacy",
      "Dental",
      "Veterinary Sciences"
    ],
    "languagesKnow": [
      "English"
    ],
    "experience": 0,
    "rating": 0,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "Education",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 0
  },
  {
    "counsellorId": "7415208802",
    "encodedId": "NzQxNTIwODgwMg",
    "firstName": "Muskan",
    "lastName": "Ahirwar",
    "city": "Indore",
    "states": [
      "Madhya Pradesh"
    ],
    "expertise": [
      "B.Sc"
    ],
    "languagesKnow": [
      "Hindi",
      "English"
    ],
    "experience": 2.5,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/7415208802/1766739886971photo.jpg",
    "organisationName": "LearnerAid",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 15000,
    "eliteAmount": 35000,
    "bioLength": 688
  },
  {
    "counsellorId": "7420801655",
    "encodedId": "NzQyMDgwMTY1NQ",
    "firstName": "Kunal",
    "lastName": "Waghmare",
    "city": "Indapur",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "English"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/7420801655/1767434966438photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 500000,
    "bioLength": 477
  },
  {
    "counsellorId": "7447325247",
    "encodedId": "NzQ0NzMyNTI0Nw",
    "firstName": "Bhushan",
    "lastName": "Mahajan",
    "city": "Nashik",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Medical",
      "Engineering",
      "Pharmacy"
    ],
    "languagesKnow": [
      "English",
      "Marathi",
      "Hindi"
    ],
    "experience": 0,
    "rating": 0,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "Admissions Simplified",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 0
  },
  {
    "counsellorId": "7447380465",
    "encodedId": "NzQ0NzM4MDQ2NQ",
    "firstName": "Harsh",
    "lastName": "Pawar",
    "city": "Amravati",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/7447380465/1767794853609photo.jpg",
    "organisationName": "Aaditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 501
  },
  {
    "counsellorId": "7499290436",
    "encodedId": "NzQ5OTI5MDQzNg",
    "firstName": "Sumit",
    "lastName": "Sahni",
    "city": "Bhadravati",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "MBA"
    ],
    "languagesKnow": [
      "English",
      "Hindi"
    ],
    "experience": 8,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/7499290436/1766739897130photo.jpg",
    "organisationName": "MBA",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 86
  },
  {
    "counsellorId": "7620515766",
    "encodedId": "NzYyMDUxNTc2Ng",
    "firstName": "Sahil",
    "lastName": "Ingale",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/7620515766/1766754522869photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 676
  },
  {
    "counsellorId": "7709034356",
    "encodedId": "NzcwOTAzNDM1Ng",
    "firstName": "Triotti",
    "lastName": "Ghosh",
    "city": "Mumbai",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "MBA"
    ],
    "languagesKnow": [
      "Hindi",
      "English",
      "Marathi"
    ],
    "experience": 0,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/7709034356/1766739909194photo.jpg",
    "organisationName": "Upgrad",
    "ratePerYear": 99,
    "plusAmount": 99,
    "proAmount": 99,
    "eliteAmount": 99,
    "bioLength": 1389
  },
  {
    "counsellorId": "7709296755",
    "encodedId": "NzcwOTI5Njc1NQ",
    "firstName": "Varad",
    "lastName": "Gaikwad",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "English",
      "Marathi"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/7709296755/1767433250667photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 676
  },
  {
    "counsellorId": "7722081555",
    "encodedId": "NzcyMjA4MTU1NQ",
    "firstName": "Poonam",
    "lastName": "Beniwal",
    "city": "Nashik",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "MBA"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi"
    ],
    "experience": 0,
    "rating": 0,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "Saksham counselling centre",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 0
  },
  {
    "counsellorId": "7756062343",
    "encodedId": "Nzc1NjA2MjM0Mw",
    "firstName": "Varad",
    "lastName": "Bhoir",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering",
      "HSC",
      "Diploma in Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 3,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/7756062343/1781599941742photo.jpg",
    "organisationName": "Career Expert MHT CET",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 25000,
    "bioLength": 1019
  },
  {
    "counsellorId": "7768038702",
    "encodedId": "Nzc2ODAzODcwMg",
    "firstName": "Manish",
    "lastName": "Sharma",
    "city": "Pune",
    "states": [
      "Maharashtra",
      "Chhattisgarh",
      "Delhi",
      "Gujarat",
      "Haryana",
      "Jharkhand",
      "Himachal Pradesh"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "B.Com",
      "B.Sc",
      "BBA",
      "BCA",
      "Dental",
      "Diploma in Engineering",
      "M.A.",
      "M.Com",
      "Medical",
      "Nursing",
      "Pharmacy"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 5,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/7768038702/1773996006382photo.jpg",
    "organisationName": "Education",
    "ratePerYear": 10000,
    "plusAmount": 10000,
    "proAmount": 30000,
    "eliteAmount": 99000,
    "bioLength": 256
  },
  {
    "counsellorId": "7770004914",
    "encodedId": "Nzc3MDAwNDkxNA",
    "firstName": "Pallavi",
    "lastName": "Rajadhyax",
    "city": "Pune",
    "states": [
      "Maharashtra",
      "Delhi",
      "Karnataka",
      "Rajasthan",
      "Jharkhand",
      "Tamil Nadu",
      "Out of India",
      "Gujarat",
      "Kerala",
      "Madhya Pradesh",
      "Goa",
      "Uttar Pradesh",
      "Assam",
      "Dadra and Nagar Haveli and Daman and Diu",
      "West Bengal",
      "Punjab",
      "Haryana",
      "Himachal Pradesh",
      "Andaman and Nicobar Islands",
      "Odisha",
      "Tripura",
      "Uttarakhand",
      "Lakshadweep",
      "Ladakh",
      "Jammu and Kashmir",
      "Arunachal Pradesh",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Puducherry",
      "Sikkim"
    ],
    "expertise": [
      "MBA",
      "HSC",
      "BBA",
      "B.Com",
      "B.A.",
      "Hotel Management",
      "Design"
    ],
    "languagesKnow": [
      "Hindi",
      "English",
      "Marathi"
    ],
    "experience": 7,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/7770004914/1768382084979photo.jpg",
    "organisationName": "First Pivot Consultants",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 1403
  },
  {
    "counsellorId": "7841055591",
    "encodedId": "Nzg0MTA1NTU5MQ",
    "firstName": "Akash",
    "lastName": "Bodakhe",
    "city": "Talegaon Dabhade",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Marathi",
      "English",
      "Hindi"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/7841055591/1767814908133photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 676
  },
  {
    "counsellorId": "7878204476",
    "encodedId": "Nzg3ODIwNDQ3Ng",
    "firstName": "Manu",
    "lastName": "Sakunia",
    "city": "Noida",
    "states": [
      "Delhi",
      "Maharashtra",
      "Karnataka",
      "Andhra Pradesh",
      "Bihar",
      "Telangana",
      "Rajasthan",
      "Jharkhand",
      "Tamil Nadu",
      "Gujarat",
      "Kerala",
      "Madhya Pradesh",
      "Goa",
      "Uttar Pradesh",
      "Dadra and Nagar Haveli and Daman and Diu",
      "Chhattisgarh",
      "Assam",
      "West Bengal",
      "Punjab",
      "Haryana",
      "Himachal Pradesh",
      "Andaman and Nicobar Islands",
      "Chandigarh",
      "Odisha",
      "Tripura",
      "Uttarakhand",
      "Arunachal Pradesh",
      "Jammu and Kashmir",
      "Ladakh",
      "Lakshadweep",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Puducherry",
      "Sikkim"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "HSC",
      "Law",
      "BBA",
      "Medical",
      "B.Com",
      "B.Sc",
      "BCA",
      "Others",
      "Pharmacy",
      "Diploma in Engineering",
      "MCA",
      "B.A.",
      "Hotel Management",
      "Nursing",
      "Dental",
      "Agriculture",
      "Animation and Multimedia",
      "M.Com",
      "M.Sc",
      "M.A.",
      "Journalism and Mass Communication",
      "Design",
      "Architecture",
      "Banking and Finance",
      "Fashion Designing",
      "Polytechnic",
      "Chartered Accountancy",
      "Cost and Management Accounting",
      "ITI",
      "Social Work",
      "B.Ed",
      "Psychology",
      "Veterinary Sciences",
      "Aviation",
      "Company Secretary",
      "Defense Services",
      "M.Ed",
      "UPSC"
    ],
    "languagesKnow": [
      "English",
      "Hindi"
    ],
    "experience": 10,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/7878204476/1768463659555photo.jpg",
    "organisationName": "My Career Saathi",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 0
  },
  {
    "counsellorId": "7970721277",
    "encodedId": "Nzk3MDcyMTI3Nw",
    "firstName": "Shubhangi",
    "lastName": "Aryan (IIM Kozhikode)",
    "city": "Delhi",
    "states": [
      "Delhi"
    ],
    "expertise": [
      "MBA",
      "Engineering",
      "HSC",
      "Journalism and Mass Communication"
    ],
    "languagesKnow": [
      "Hindi",
      "English"
    ],
    "experience": 2,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/7970721277/1767627816567photo.jpg",
    "organisationName": "IIM Kozhikode",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 841
  },
  {
    "counsellorId": "7974508936",
    "encodedId": "Nzk3NDUwODkzNg",
    "firstName": "Radhika Santosh",
    "lastName": "Upadhyay",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "MBA"
    ],
    "languagesKnow": [
      "Hindi",
      "English",
      "Marathi"
    ],
    "experience": 0,
    "rating": 0,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "Sachi Institutes",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 0
  },
  {
    "counsellorId": "8080471633",
    "encodedId": "ODA4MDQ3MTYzMw",
    "firstName": "Shravan",
    "lastName": "Swami",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "English",
      "Hindi",
      "Marathi"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/8080471633/1767434123845photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 501
  },
  {
    "counsellorId": "8106254580",
    "encodedId": "ODEwNjI1NDU4MA",
    "firstName": "Uday",
    "lastName": "Labishetty",
    "city": "Pune",
    "states": [
      "Delhi",
      "Karnataka",
      "Maharashtra",
      "Tamil Nadu"
    ],
    "expertise": [
      "Medical",
      "Engineering",
      "MBA"
    ],
    "languagesKnow": [
      "Telugu",
      "English",
      "Hindi"
    ],
    "experience": 5,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/8106254580/1766739947546photo.jpg",
    "organisationName": "Hyderabad",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 20000,
    "eliteAmount": 980000,
    "bioLength": 259
  },
  {
    "counsellorId": "8108109581",
    "encodedId": "ODEwODEwOTU4MQ",
    "firstName": "Aniket",
    "lastName": "Pilley",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "Law"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 2,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/8108109581/1766739958473photo.jpg",
    "organisationName": "Aspire Edutech Services",
    "ratePerYear": 2999,
    "plusAmount": 2999,
    "proAmount": 9999,
    "eliteAmount": 24999,
    "bioLength": 681
  },
  {
    "counsellorId": "8149212021",
    "encodedId": "ODE0OTIxMjAyMQ",
    "firstName": "Himanshu",
    "lastName": "Tatte",
    "city": "Warud",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/8149212021/1767804819480photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 500
  },
  {
    "counsellorId": "8177842601",
    "encodedId": "ODE3Nzg0MjYwMQ",
    "firstName": "Nikhil",
    "lastName": "Jain",
    "city": "Nashik",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "MBA",
      "Engineering",
      "Medical"
    ],
    "languagesKnow": [
      "Hindi",
      "English",
      "Tamil",
      "Marathi"
    ],
    "experience": 9,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "Resonance Classes",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 30000,
    "bioLength": 400
  },
  {
    "counsellorId": "8263029775",
    "encodedId": "ODI2MzAyOTc3NQ",
    "firstName": "Kasturi",
    "lastName": "Deshpande",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/8263029775/1779271217017photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 577
  },
  {
    "counsellorId": "8265040588",
    "encodedId": "ODI2NTA0MDU4OA",
    "firstName": "Piyush",
    "lastName": "Pansare",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/8265040588/1767805739262photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 501
  },
  {
    "counsellorId": "8308938331",
    "encodedId": "ODMwODkzODMzMQ",
    "firstName": "Shristi",
    "lastName": "Goutam",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "MBA"
    ],
    "languagesKnow": [
      "English",
      "Hindi"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/8308938331/1763741741438photo.jpg",
    "organisationName": "Symbiosis (SCMHRD)",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 1047
  },
  {
    "counsellorId": "8369698025",
    "encodedId": "ODM2OTY5ODAyNQ",
    "firstName": "Chetan",
    "lastName": "Bhandari",
    "city": "Mumbai",
    "states": [
      "Maharashtra",
      "Gujarat"
    ],
    "expertise": [
      "Medical",
      "HSC",
      "Hotel Management",
      "Animation and Multimedia"
    ],
    "languagesKnow": [
      "Hindi",
      "English"
    ],
    "experience": 0,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "Map your career",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 59
  },
  {
    "counsellorId": "8432095801",
    "encodedId": "ODQzMjA5NTgwMQ",
    "firstName": "Ganesh",
    "lastName": "Pokharkar",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering",
      "HSC",
      "Diploma in Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 2,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "Career Expert MHTCET Counselling",
    "ratePerYear": 4000,
    "plusAmount": 4000,
    "proAmount": 10000,
    "eliteAmount": 25000,
    "bioLength": 1286
  },
  {
    "counsellorId": "8483854004",
    "encodedId": "ODQ4Mzg1NDAwNA",
    "firstName": "Shaikh Mussadique",
    "lastName": "Ahmed Mushtaque",
    "city": "Aurangabad",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "HSC",
      "Medical",
      "Pharmacy",
      "B.Sc",
      "BCA",
      "Nursing",
      "Diploma in Engineering",
      "M.Sc",
      "Defense Services",
      "UPSC",
      "Social Work",
      "B.Ed"
    ],
    "languagesKnow": [
      "English",
      "Hindi",
      "Marathi"
    ],
    "experience": 7,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/8483854004/1777728176638photo.jpg",
    "organisationName": "Maulana azad college of arts science and Commerce",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 871
  },
  {
    "counsellorId": "8485841622",
    "encodedId": "ODQ4NTg0MTYyMg",
    "firstName": "Sumedh",
    "lastName": "Rajadhyax",
    "city": "Pune",
    "states": [
      "Maharashtra",
      "Delhi",
      "Karnataka",
      "Andhra Pradesh",
      "Bihar",
      "Telangana",
      "Rajasthan",
      "Jharkhand",
      "Tamil Nadu",
      "Out of India",
      "Gujarat",
      "Kerala",
      "Madhya Pradesh",
      "Uttar Pradesh",
      "Assam",
      "Chhattisgarh",
      "Goa",
      "Dadra and Nagar Haveli and Daman and Diu",
      "Himachal Pradesh",
      "West Bengal",
      "Andaman and Nicobar Islands",
      "Chandigarh",
      "Haryana",
      "Odisha",
      "Punjab",
      "Tripura",
      "Uttarakhand",
      "Arunachal Pradesh",
      "Jammu and Kashmir",
      "Ladakh",
      "Lakshadweep",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Puducherry",
      "Sikkim"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "HSC",
      "Law",
      "BCA",
      "Medical",
      "BBA",
      "B.Com",
      "B.Sc",
      "Pharmacy",
      "MCA",
      "Dental",
      "Others",
      "B.A.",
      "Hotel Management",
      "M.Com",
      "M.Sc",
      "Agriculture",
      "Animation and Multimedia",
      "M.A.",
      "Banking and Finance",
      "Cost and Management Accounting",
      "Fashion Designing",
      "Journalism and Mass Communication",
      "Polytechnic",
      "Architecture",
      "Chartered Accountancy",
      "Design",
      "UPSC",
      "Veterinary Sciences",
      "Aviation",
      "B.Ed",
      "Company Secretary",
      "Defense Services",
      "Psychology"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 7,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/8485841622/1765367270380photo.jpg",
    "organisationName": "First Pivot Consultants",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 1481
  },
  {
    "counsellorId": "8554998152",
    "encodedId": "ODU1NDk5ODE1Mg",
    "firstName": "Narendra",
    "lastName": "Jejurkar",
    "city": "Nashik",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Others"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 25,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "Shree jay Gajanan classes",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 1166
  },
  {
    "counsellorId": "8624989351",
    "encodedId": "ODYyNDk4OTM1MQ",
    "firstName": "Vedant",
    "lastName": "Hongunte",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/8624989351/1767175685993photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 677
  },
  {
    "counsellorId": "8637055724",
    "encodedId": "ODYzNzA1NTcyNA",
    "firstName": "Aditya",
    "lastName": "Sahani",
    "city": "Pune",
    "states": [
      "Maharashtra",
      "Delhi",
      "Bihar",
      "Rajasthan",
      "Gujarat",
      "Madhya Pradesh",
      "Uttar Pradesh",
      "West Bengal",
      "Punjab",
      "Haryana",
      "Himachal Pradesh",
      "Meghalaya",
      "Mizoram",
      "Manipur",
      "Ladakh",
      "Jammu and Kashmir",
      "Nagaland",
      "Sikkim"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "English"
    ],
    "experience": 2,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/8637055724/1774981652101photo.jpg",
    "organisationName": "AdityaCoep",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 5000,
    "eliteAmount": 30000,
    "bioLength": 0
  },
  {
    "counsellorId": "8766578668",
    "encodedId": "ODc2NjU3ODY2OA",
    "firstName": "Sushil",
    "lastName": "Dange",
    "city": "Aurangabad",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Marathi",
      "Hindi",
      "English"
    ],
    "experience": 25,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "Dange's Academy",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 0
  },
  {
    "counsellorId": "8767318431",
    "encodedId": "ODc2NzMxODQzMQ",
    "firstName": "Shreyasi",
    "lastName": "Suryawanshi",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 2,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/8767318431/1767804221777photo.jpg",
    "organisationName": "Aaditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 799
  },
  {
    "counsellorId": "8767333039",
    "encodedId": "ODc2NzMzMzAzOQ",
    "firstName": "Ishan",
    "lastName": "Pawar",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "Law"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 2,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/8767333039/1763190847340photo.jpg",
    "organisationName": "Aspire Edu-tech Services",
    "ratePerYear": 999,
    "plusAmount": 999,
    "proAmount": 4999,
    "eliteAmount": 14999,
    "bioLength": 642
  },
  {
    "counsellorId": "8767388968",
    "encodedId": "ODc2NzM4ODk2OA",
    "firstName": "Prem",
    "lastName": "Devkate",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Marathi",
      "English",
      "Hindi"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/8767388968/1767793189074photo.jpg",
    "organisationName": "Aadity coep",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 485
  },
  {
    "counsellorId": "8770579905",
    "encodedId": "ODc3MDU3OTkwNQ",
    "firstName": "Kanishq",
    "lastName": "Rajput",
    "city": "Pune",
    "states": [
      "Maharashtra",
      "Delhi",
      "Karnataka",
      "Out of India",
      "Uttar Pradesh",
      "Chhattisgarh",
      "Gujarat",
      "Goa",
      "Tamil Nadu",
      "Telangana",
      "Rajasthan",
      "Madhya Pradesh"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "BBA",
      "Pharmacy",
      "BCA",
      "B.Com",
      "Diploma in Engineering",
      "B.Sc",
      "Law",
      "UPSC",
      "Banking and Finance",
      "Journalism and Mass Communication",
      "M.Com",
      "Cost and Management Accounting",
      "HSC",
      "MCA",
      "Hotel Management"
    ],
    "languagesKnow": [
      "English",
      "Hindi"
    ],
    "experience": 0,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/8770579905/1766739996560photo.jpg",
    "organisationName": "Dregeup education consultancy",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 50000,
    "bioLength": 515
  },
  {
    "counsellorId": "8793063029",
    "encodedId": "ODc5MzA2MzAyOQ",
    "firstName": "Swayam",
    "lastName": "Tehare",
    "city": "Mumbai",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "English",
      "Hindi",
      "Marathi"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/8793063029/1784905801590photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 591
  },
  {
    "counsellorId": "8830489930",
    "encodedId": "ODgzMDQ4OTkzMA",
    "firstName": "Amrita",
    "lastName": "Daga",
    "city": "Pune",
    "states": [
      "Maharashtra",
      "Delhi",
      "Karnataka",
      "Andhra Pradesh",
      "Bihar",
      "Telangana",
      "Jharkhand",
      "Rajasthan",
      "Tamil Nadu",
      "Out of India",
      "Gujarat",
      "Kerala",
      "Madhya Pradesh",
      "Uttar Pradesh",
      "Assam",
      "Chhattisgarh",
      "Goa",
      "Dadra and Nagar Haveli and Daman and Diu",
      "Himachal Pradesh",
      "West Bengal",
      "Andaman and Nicobar Islands",
      "Chandigarh",
      "Haryana",
      "Odisha",
      "Punjab",
      "Tripura",
      "Uttarakhand",
      "Arunachal Pradesh",
      "Jammu and Kashmir",
      "Ladakh",
      "Lakshadweep",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Puducherry",
      "Sikkim"
    ],
    "expertise": [
      "Engineering",
      "HSC",
      "Law",
      "BBA",
      "MBA",
      "Medical",
      "B.Com",
      "BCA",
      "B.Sc",
      "Pharmacy",
      "Diploma in Engineering",
      "Others",
      "MCA",
      "Nursing",
      "Dental",
      "B.A.",
      "Hotel Management",
      "Agriculture",
      "Animation and Multimedia",
      "Banking and Finance",
      "Chartered Accountancy",
      "Cost and Management Accounting",
      "Fashion Designing",
      "Journalism and Mass Communication",
      "Polytechnic",
      "Architecture",
      "Design",
      "Veterinary Sciences",
      "Aviation",
      "Company Secretary",
      "Defense Services",
      "B.Ed",
      "Psychology",
      "Social Work"
    ],
    "languagesKnow": [
      "Hindi",
      "English"
    ],
    "experience": 6,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "Aspire2Inspire Careers",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 1493
  },
  {
    "counsellorId": "8830638488",
    "encodedId": "ODgzMDYzODQ4OA",
    "firstName": "Dr.Yogesh",
    "lastName": "Wankhede",
    "city": "Nashik",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "HSC",
      "Medical",
      "B.Sc",
      "Others",
      "B.Com",
      "Design"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 25,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/8830638488/1771687605677photo.jpg",
    "organisationName": "Mindsearch Counseling",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 15000,
    "eliteAmount": 50000,
    "bioLength": 992
  },
  {
    "counsellorId": "8855019283",
    "encodedId": "ODg1NTAxOTI4Mw",
    "firstName": "Mohammad",
    "lastName": "Shaikh",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering",
      "HSC"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/8855019283/1768735609592photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 679
  },
  {
    "counsellorId": "8856062360",
    "encodedId": "ODg1NjA2MjM2MA",
    "firstName": "Janhavi",
    "lastName": "Mokashi",
    "city": "Mumbai",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering",
      "HSC"
    ],
    "languagesKnow": [
      "Marathi",
      "Hindi",
      "English"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/8856062360/1767432535835photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 678
  },
  {
    "counsellorId": "8888817273",
    "encodedId": "ODg4ODgxNzI3Mw",
    "firstName": "Kalpesh",
    "lastName": "Jejurkar",
    "city": "Nashik",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "MBA",
      "HSC",
      "BBA",
      "Others",
      "B.Com",
      "BCA",
      "Social Work"
    ],
    "languagesKnow": [
      "English",
      "Hindi",
      "Marathi"
    ],
    "experience": 15,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "Shree Gajanan Classes",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 828
  },
  {
    "counsellorId": "8999897393",
    "encodedId": "ODk5OTg5NzM5Mw",
    "firstName": "Tanishka",
    "lastName": "Jadhavar",
    "city": "Kolhapur",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/8999897393/1769695585910photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 462
  },
  {
    "counsellorId": "9011432704",
    "encodedId": "OTAxMTQzMjcwNA",
    "firstName": "Abhishek",
    "lastName": "Gite",
    "city": "Nashik",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9011432704/1768385604610photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 543
  },
  {
    "counsellorId": "9028482482",
    "encodedId": "OTAyODQ4MjQ4Mg",
    "firstName": "Atul",
    "lastName": "Kulkarni",
    "city": "Aurangabad",
    "states": [
      "Maharashtra",
      "Karnataka",
      "Andhra Pradesh",
      "Telangana",
      "Out of India",
      "Puducherry"
    ],
    "expertise": [
      "Engineering",
      "Medical",
      "MBA",
      "Pharmacy",
      "BBA",
      "B.Sc",
      "BCA",
      "Diploma in Engineering",
      "MCA",
      "Agriculture",
      "Architecture",
      "Hotel Management",
      "Dental",
      "Design",
      "Fashion Designing",
      "Polytechnic"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 30,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "Vivekanand Career Academy, Chhatrapati Sambhajinagar",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 499
  },
  {
    "counsellorId": "9075584663",
    "encodedId": "OTA3NTU4NDY2Mw",
    "firstName": "Vedant",
    "lastName": "Deshmukh",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Marathi",
      "Hindi",
      "English"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9075584663/1767794103454photo.jpg",
    "organisationName": "Aaditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 506
  },
  {
    "counsellorId": "9096773772",
    "encodedId": "OTA5Njc3Mzc3Mg",
    "firstName": "Aarav",
    "lastName": "Kush",
    "city": "Nashik",
    "states": [
      "Maharashtra",
      "Delhi",
      "Andhra Pradesh",
      "Karnataka",
      "Rajasthan",
      "Bihar",
      "Gujarat",
      "Telangana",
      "Jharkhand",
      "Out of India",
      "Tamil Nadu",
      "Madhya Pradesh",
      "Kerala",
      "Goa",
      "Uttar Pradesh",
      "Punjab",
      "Assam",
      "Chhattisgarh",
      "West Bengal",
      "Dadra and Nagar Haveli and Daman and Diu",
      "Haryana",
      "Himachal Pradesh",
      "Odisha",
      "Chandigarh",
      "Uttarakhand",
      "Tripura",
      "Andaman and Nicobar Islands",
      "Jammu and Kashmir",
      "Arunachal Pradesh",
      "Ladakh",
      "Manipur",
      "Sikkim",
      "Meghalaya",
      "Nagaland",
      "Puducherry",
      "Mizoram",
      "Lakshadweep"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "Medical",
      "B.Sc",
      "Pharmacy",
      "BCA",
      "B.Com",
      "Others",
      "BBA",
      "MCA",
      "Diploma in Engineering",
      "B.A.",
      "M.Sc",
      "M.A.",
      "M.Com",
      "Architecture",
      "Banking and Finance",
      "B.Ed",
      "Psychology",
      "M.Ed"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 10,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "Edu2career",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 15000,
    "eliteAmount": 50000,
    "bioLength": 316
  },
  {
    "counsellorId": "9110709417",
    "encodedId": "OTExMDcwOTQxNw",
    "firstName": "Manasa",
    "lastName": "Ambidi",
    "city": "Indore",
    "states": [
      "Maharashtra",
      "Delhi",
      "Andhra Pradesh",
      "Telangana",
      "Gujarat",
      "Madhya Pradesh",
      "Uttar Pradesh"
    ],
    "expertise": [
      "MBA",
      "Engineering",
      "BBA",
      "B.Com",
      "B.Sc",
      "Diploma in Engineering",
      "M.Sc",
      "B.A."
    ],
    "languagesKnow": [
      "Hindi",
      "English",
      "Telugu"
    ],
    "experience": 4.5,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9110709417/1766740029943photo.jpg",
    "organisationName": "learnerAid",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 15000,
    "eliteAmount": 35000,
    "bioLength": 844
  },
  {
    "counsellorId": "9112205455",
    "encodedId": "OTExMjIwNTQ1NQ",
    "firstName": "Tareq",
    "lastName": "Momin",
    "city": "Aurangabad Maharashtra",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering",
      "Pharmacy",
      "Diploma in Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 3,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "Shiksha Foundation",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 0
  },
  {
    "counsellorId": "9146223245",
    "encodedId": "OTE0NjIyMzI0NQ",
    "firstName": "Sarthak",
    "lastName": "Bhambare",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "English",
      "Hindi",
      "Marathi"
    ],
    "experience": 2,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9146223245/1767803729648photo.jpg",
    "organisationName": "Procounsel",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 562
  },
  {
    "counsellorId": "9153492204",
    "encodedId": "OTE1MzQ5MjIwNA",
    "firstName": "Ujjawal",
    "lastName": "Swaraj",
    "city": "Patna",
    "states": [
      "Bihar"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "Medical",
      "BBA",
      "Dental",
      "Nursing",
      "Pharmacy",
      "B.Com",
      "Agriculture",
      "B.Sc",
      "BCA",
      "Architecture",
      "B.A.",
      "Diploma in Engineering",
      "Fashion Designing",
      "Hotel Management",
      "ITI",
      "Law",
      "M.A.",
      "M.Com",
      "MCA",
      "Polytechnic",
      "Veterinary Sciences",
      "Aviation",
      "B.Ed",
      "Journalism and Mass Communication",
      "M.Ed",
      "M.Sc",
      "Psychology",
      "Others"
    ],
    "languagesKnow": [
      "English"
    ],
    "experience": 0,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "Edu Professionalist",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 254
  },
  {
    "counsellorId": "9156921114",
    "encodedId": "OTE1NjkyMTExNA",
    "firstName": "Dhananjay",
    "lastName": "Wagh",
    "city": "Aurangabad",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Marathi",
      "Hindi",
      "English"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9156921114/1767437855010photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 510
  },
  {
    "counsellorId": "9175537756",
    "encodedId": "OTE3NTUzNzc1Ng",
    "firstName": "Aadesh Prasanna",
    "lastName": "Naieek",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "HSC",
      "MBA",
      "Medical",
      "Law",
      "BBA",
      "B.Sc",
      "Others",
      "B.Com",
      "BCA",
      "Pharmacy",
      "Diploma in Engineering",
      "MCA",
      "B.A.",
      "Nursing",
      "Agriculture",
      "Hotel Management",
      "M.Sc",
      "Dental",
      "M.A.",
      "M.Com",
      "Animation and Multimedia",
      "Architecture",
      "Banking and Finance",
      "Design",
      "Fashion Designing",
      "Defense Services",
      "ITI",
      "Journalism and Mass Communication",
      "B.Ed",
      "Chartered Accountancy",
      "Polytechnic",
      "Psychology",
      "Social Work",
      "UPSC",
      "Cost and Management Accounting",
      "Aviation",
      "M.Ed",
      "Veterinary Sciences",
      "Company Secretary",
      "Engineering"
    ],
    "languagesKnow": [
      "Marathi",
      "Hindi",
      "English"
    ],
    "experience": 0,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "Naik Tutorials",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 0
  },
  {
    "counsellorId": "9209224214",
    "encodedId": "OTIwOTIyNDIxNA",
    "firstName": "Pranavi",
    "lastName": "Shinde",
    "city": "Nagpur",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "English",
      "Marathi"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9209224214/1767442038067photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 678
  },
  {
    "counsellorId": "9209334720",
    "encodedId": "OTIwOTMzNDcyMA",
    "firstName": "Saksham",
    "lastName": "Ramteke",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "English",
      "Marathi"
    ],
    "experience": 1,
    "rating": 0,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9209334720/1767432170116photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 493
  },
  {
    "counsellorId": "9229097562",
    "encodedId": "OTIyOTA5NzU2Mg",
    "firstName": "Rashid",
    "lastName": "Sabri",
    "city": "Patna",
    "states": [
      "Maharashtra",
      "Andhra Pradesh",
      "Bihar",
      "Delhi",
      "Karnataka",
      "Jharkhand",
      "Kerala",
      "Telangana",
      "Out of India",
      "Tamil Nadu",
      "Assam",
      "Rajasthan",
      "Goa",
      "Uttar Pradesh",
      "Chhattisgarh",
      "Himachal Pradesh",
      "West Bengal",
      "Andaman and Nicobar Islands",
      "Chandigarh",
      "Gujarat",
      "Haryana",
      "Madhya Pradesh",
      "Odisha",
      "Punjab",
      "Uttarakhand",
      "Arunachal Pradesh",
      "Dadra and Nagar Haveli and Daman and Diu",
      "Jammu and Kashmir",
      "Ladakh",
      "Lakshadweep",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Puducherry",
      "Sikkim",
      "Tripura"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "Medical",
      "Nursing",
      "Pharmacy",
      "B.Com",
      "BCA",
      "Law"
    ],
    "languagesKnow": [
      "Hindi",
      "English"
    ],
    "experience": 0,
    "rating": 0,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9229097562/1766740072065photo.jpg",
    "organisationName": "Edu Professionalist",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 495
  },
  {
    "counsellorId": "9284148679",
    "encodedId": "OTI4NDE0ODY3OQ",
    "firstName": "Ashitosh",
    "lastName": "Said",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Marathi",
      "Hindi"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9284148679/1767176255799photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 565
  },
  {
    "counsellorId": "9284385106",
    "encodedId": "OTI4NDM4NTEwNg",
    "firstName": "Swarup",
    "lastName": "Sonawane",
    "city": "Aurangabad",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "English",
      "Marathi"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9284385106/1768751346648photo.jpg",
    "organisationName": "Aaditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 677
  },
  {
    "counsellorId": "9284592278",
    "encodedId": "OTI4NDU5MjI3OA",
    "firstName": "Anuja",
    "lastName": "Chopade",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 676
  },
  {
    "counsellorId": "9307288022",
    "encodedId": "OTMwNzI4ODAyMg",
    "firstName": "Darshan",
    "lastName": "Gangapurwar",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "English",
      "Hindi"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9307288022/1767437169276photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 678
  },
  {
    "counsellorId": "9309186572",
    "encodedId": "OTMwOTE4NjU3Mg",
    "firstName": "Urjela",
    "lastName": "Yemulwar",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "English",
      "Hindi",
      "Marathi",
      "Telugu"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9309186572/1767434375440photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 677
  },
  {
    "counsellorId": "9309455286",
    "encodedId": "OTMwOTQ1NTI4Ng",
    "firstName": "Rushikesh",
    "lastName": "Chaudhari",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "English",
      "Hindi",
      "Marathi"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9309455286/1767806654041photo.jpg",
    "organisationName": "Aaditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 615
  },
  {
    "counsellorId": "9310594089",
    "encodedId": "OTMxMDU5NDA4OQ",
    "firstName": "Vikash",
    "lastName": "Kumar",
    "city": "Bangalore Urban",
    "states": [
      "Maharashtra",
      "Karnataka",
      "Bihar",
      "Jharkhand",
      "Uttar Pradesh",
      "Tamil Nadu"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "Medical",
      "BBA",
      "Dental",
      "Nursing",
      "Pharmacy",
      "Agriculture",
      "B.Com",
      "BCA",
      "Animation and Multimedia",
      "Design",
      "MCA",
      "Law",
      "Hotel Management",
      "Fashion Designing",
      "Diploma in Engineering",
      "Journalism and Mass Communication"
    ],
    "languagesKnow": [
      "Hindi",
      "English"
    ],
    "experience": 10,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9310594089/1766740122287photo.jpg",
    "organisationName": "PROCOUNSEL",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 175
  },
  {
    "counsellorId": "9321230881",
    "encodedId": "OTMyMTIzMDg4MQ",
    "firstName": "Riddhi",
    "lastName": "Dhoble",
    "city": "Mumbai",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Marathi",
      "Hindi",
      "English"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9321230881/1767441085683photo.jpg",
    "organisationName": "Aaditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 440
  },
  {
    "counsellorId": "9322149557",
    "encodedId": "OTMyMjE0OTU1Nw",
    "firstName": "Dr Dhananjay",
    "lastName": "Khanke",
    "city": "Nashik",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Medical"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 8,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9322149557/1772986741667photo.jpg",
    "organisationName": "Disha Educare Institute",
    "ratePerYear": 10000,
    "plusAmount": 10000,
    "proAmount": 50000,
    "eliteAmount": 100000,
    "bioLength": 1213
  },
  {
    "counsellorId": "9322737690",
    "encodedId": "OTMyMjczNzY5MA",
    "firstName": "Ram",
    "lastName": "Khade",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "BBA",
      "Medical",
      "Pharmacy",
      "B.Com",
      "Law",
      "BCA",
      "MCA",
      "Hotel Management",
      "B.A.",
      "ITI"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 2,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9322737690/1770048936772photo.jpg",
    "organisationName": "Aspire Edutech Services",
    "ratePerYear": 999,
    "plusAmount": 999,
    "proAmount": 4999,
    "eliteAmount": 24999,
    "bioLength": 428
  },
  {
    "counsellorId": "9403573312",
    "encodedId": "OTQwMzU3MzMxMg",
    "firstName": "Shrikant",
    "lastName": "Magar",
    "city": "Aurangabad",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "English",
      "Marathi"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9403573312/1768750482565photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 679
  },
  {
    "counsellorId": "9405182805",
    "encodedId": "OTQwNTE4MjgwNQ",
    "firstName": "Agastya",
    "lastName": "Jadhav",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "English",
      "Hindi",
      "Marathi"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9405182805/1767438005526photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 499
  },
  {
    "counsellorId": "9405284764",
    "encodedId": "OTQwNTI4NDc2NA",
    "firstName": "Sagar",
    "lastName": "Akode",
    "city": "Jalna",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9405284764/1767431607978photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 513
  },
  {
    "counsellorId": "9503053901",
    "encodedId": "OTUwMzA1MzkwMQ",
    "firstName": "Yuvraj",
    "lastName": "Baglane",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "English",
      "Hindi",
      "Marathi"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9503053901/1767804182188photo.jpg",
    "organisationName": "Aaditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 554
  },
  {
    "counsellorId": "9503482848",
    "encodedId": "OTUwMzQ4Mjg0OA",
    "firstName": "Ritika",
    "lastName": "Jain",
    "city": "Pune",
    "states": [
      "Maharashtra",
      "Karnataka",
      "Delhi"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "Medical",
      "Law"
    ],
    "languagesKnow": [
      "Hindi",
      "English"
    ],
    "experience": 17,
    "rating": 5,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9503482848/1780645740677photo.jpg",
    "organisationName": "Procounsel",
    "ratePerYear": 10000,
    "plusAmount": 10000,
    "proAmount": 25000,
    "eliteAmount": 50000,
    "bioLength": 154
  },
  {
    "counsellorId": "9511606713",
    "encodedId": "OTUxMTYwNjcxMw",
    "firstName": "Jitesh",
    "lastName": "Gawande",
    "city": "Aurangabad",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9511606713/1767438173556photo.jpg",
    "organisationName": "Aaditya coep",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 677
  },
  {
    "counsellorId": "9529236959",
    "encodedId": "OTUyOTIzNjk1OQ",
    "firstName": "Samyak",
    "lastName": "Jain",
    "city": "Pune",
    "states": [
      "Maharashtra",
      "Karnataka"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "Law"
    ],
    "languagesKnow": [
      "Hindi",
      "English",
      "Marathi"
    ],
    "experience": 8,
    "rating": 5,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9529236959/1766740149071photo.jpg",
    "organisationName": "Elevate Education Consultancy",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 195
  },
  {
    "counsellorId": "9552888995",
    "encodedId": "OTU1Mjg4ODk5NQ",
    "firstName": "Dr. Narendra",
    "lastName": "Baheti",
    "city": "Aurangabad",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Others"
    ],
    "languagesKnow": [
      "Marathi",
      "English",
      "Hindi"
    ],
    "experience": 12,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "ANANT PRADHNYA COACHING ACADEMY",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 0
  },
  {
    "counsellorId": "9604595303",
    "encodedId": "OTYwNDU5NTMwMw",
    "firstName": "Vallabh",
    "lastName": "Chaudhari",
    "city": "Sambhajinagar",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "BBA",
      "B.Sc",
      "BCA",
      "Diploma in Engineering",
      "Polytechnic",
      "ITI"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 4,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "Education Consultant & Career Counseling.",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 549
  },
  {
    "counsellorId": "9699431450",
    "encodedId": "OTY5OTQzMTQ1MA",
    "firstName": "Samiksha",
    "lastName": "Kanande",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9699431450/1769422770699photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 514
  },
  {
    "counsellorId": "9730221230",
    "encodedId": "OTczMDIyMTIzMA",
    "firstName": "Samruddhi",
    "lastName": "Kasar",
    "city": "Shirdi",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Marathi"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9730221230/1767803793006photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 680
  },
  {
    "counsellorId": "9764819291",
    "encodedId": "OTc2NDgxOTI5MQ",
    "firstName": "Atharva",
    "lastName": "Sakhare",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "Hindi",
      "English",
      "Marathi"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9764819291/1780576168825photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 642
  },
  {
    "counsellorId": "9766466691",
    "encodedId": "OTc2NjQ2NjY5MQ",
    "firstName": "Vaibhav Sambhaji",
    "lastName": "Patil",
    "city": "Nanded",
    "states": [
      "Maharashtra",
      "Karnataka",
      "Telangana",
      "Andhra Pradesh",
      "Kerala",
      "Out of India",
      "Rajasthan",
      "Uttar Pradesh"
    ],
    "expertise": [
      "Medical",
      "Engineering",
      "Dental",
      "Nursing",
      "Pharmacy",
      "Veterinary Sciences"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 5,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9766466691/1766740158814photo.jpg",
    "organisationName": "VIBRANT CAREER GUIDANCE NANDED",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 0
  },
  {
    "counsellorId": "9766902189",
    "encodedId": "OTc2NjkwMjE4OQ",
    "firstName": "Manas",
    "lastName": "Pradhan",
    "city": "Pune",
    "states": [
      "Maharashtra",
      "Delhi",
      "Karnataka"
    ],
    "expertise": [
      "MBA",
      "Engineering",
      "Law"
    ],
    "languagesKnow": [
      "Hindi",
      "English",
      "Marathi"
    ],
    "experience": 17,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9766902189/1766740182535photo.jpg",
    "organisationName": "Dregup education",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 1236
  },
  {
    "counsellorId": "9822181192",
    "encodedId": "OTgyMjE4MTE5Mg",
    "firstName": "Shaikh Ateeque Ur Rahman",
    "lastName": "Shaikh",
    "city": "Aurangabad",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering",
      "HSC",
      "Others",
      "MBA",
      "Medical",
      "Law",
      "Pharmacy",
      "BBA",
      "B.Sc",
      "BCA",
      "Diploma in Engineering",
      "Nursing",
      "B.Com",
      "MCA",
      "Agriculture",
      "Architecture",
      "Hotel Management",
      "B.A.",
      "M.Sc",
      "UPSC",
      "M.A.",
      "M.Com",
      "Banking and Finance",
      "Fashion Designing",
      "Polytechnic",
      "Social Work",
      "B.Ed",
      "Psychology",
      "M.Ed"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 15,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9822181192/1780377217095photo.jpg",
    "organisationName": "Education Consultant",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 892
  },
  {
    "counsellorId": "9908529524",
    "encodedId": "OTkwODUyOTUyNA",
    "firstName": "Bhushan",
    "lastName": "Shinde",
    "city": "Pune",
    "states": [
      "Maharashtra",
      "Delhi",
      "Karnataka",
      "Andhra Pradesh",
      "Bihar",
      "Telangana",
      "Jharkhand",
      "Rajasthan",
      "Tamil Nadu",
      "Out of India",
      "Gujarat",
      "Kerala",
      "Madhya Pradesh",
      "Uttar Pradesh",
      "Assam",
      "Chhattisgarh",
      "Goa",
      "Dadra and Nagar Haveli and Daman and Diu",
      "Himachal Pradesh",
      "West Bengal",
      "Andaman and Nicobar Islands",
      "Chandigarh",
      "Haryana",
      "Odisha",
      "Punjab",
      "Tripura",
      "Uttarakhand",
      "Arunachal Pradesh",
      "Jammu and Kashmir",
      "Ladakh",
      "Lakshadweep",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Puducherry",
      "Sikkim"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "HSC",
      "Law",
      "BBA",
      "Medical",
      "B.Com",
      "BCA",
      "B.Sc",
      "Pharmacy",
      "Diploma in Engineering",
      "Others",
      "MCA",
      "Nursing",
      "Dental",
      "B.A.",
      "Hotel Management",
      "M.Com",
      "M.Sc",
      "Agriculture",
      "Animation and Multimedia",
      "M.A.",
      "Banking and Finance",
      "Chartered Accountancy",
      "Cost and Management Accounting",
      "Fashion Designing",
      "ITI",
      "Journalism and Mass Communication",
      "Polytechnic",
      "Architecture",
      "Design",
      "UPSC",
      "Veterinary Sciences",
      "Aviation",
      "B.Ed",
      "Company Secretary",
      "Defense Services",
      "M.Ed",
      "Psychology",
      "Social Work"
    ],
    "languagesKnow": [
      "English",
      "Hindi",
      "Marathi"
    ],
    "experience": 15,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9908529524/1766403712129photo.jpg",
    "organisationName": "MyAha CareerPoint",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 491
  },
  {
    "counsellorId": "9917070979",
    "encodedId": "OTkxNzA3MDk3OQ",
    "firstName": "Ibraheem",
    "lastName": "Khan",
    "city": "Pune",
    "states": [
      "Maharashtra",
      "Delhi"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "BBA"
    ],
    "languagesKnow": [
      "Hindi",
      "English"
    ],
    "experience": 5,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9917070979/1768593394195photo.jpg",
    "organisationName": "PI CAREER CONSULTANTS",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 50000,
    "bioLength": 401
  },
  {
    "counsellorId": "9922085328",
    "encodedId": "OTkyMjA4NTMyOA",
    "firstName": "RAJRATN",
    "lastName": "GAIKWAD",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "English",
      "Hindi",
      "Marathi"
    ],
    "experience": 1,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9922085328/1767803531682photo.jpg",
    "organisationName": "Aditya COEP",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 604
  },
  {
    "counsellorId": "9923144306",
    "encodedId": "OTkyMzE0NDMwNg",
    "firstName": "Rupali S",
    "lastName": "Rathore",
    "city": "Pune",
    "states": [
      "Maharashtra",
      "Uttar Pradesh",
      "Delhi",
      "Rajasthan",
      "Telangana",
      "Bihar",
      "Gujarat",
      "Madhya Pradesh",
      "Tamil Nadu",
      "Karnataka",
      "Kerala",
      "Jharkhand",
      "Odisha",
      "Chhattisgarh",
      "Puducherry",
      "Sikkim",
      "Manipur",
      "Meghalaya",
      "Out of India"
    ],
    "expertise": [
      "Engineering",
      "Medical",
      "HSC",
      "Others",
      "B.Sc",
      "BBA",
      "Dental",
      "Diploma in Engineering",
      "Design",
      "Polytechnic",
      "Fashion Designing",
      "Aviation",
      "B.Ed"
    ],
    "languagesKnow": [
      "Hindi",
      "English"
    ],
    "experience": 0,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9923144306/1784632381297photo.jpg",
    "organisationName": "Career craftyouth",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 826
  },
  {
    "counsellorId": "9960166723",
    "encodedId": "OTk2MDE2NjcyMw",
    "firstName": "Anirudh",
    "lastName": "Kumar",
    "city": "Pune",
    "states": [
      "Maharashtra",
      "Delhi",
      "Tamil Nadu",
      "Kerala",
      "Goa",
      "Uttar Pradesh",
      "West Bengal",
      "Punjab",
      "Chandigarh",
      "Haryana"
    ],
    "expertise": [
      "Engineering"
    ],
    "languagesKnow": [
      "English",
      "Hindi"
    ],
    "experience": 12,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "Merchant Navy",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 539
  },
  {
    "counsellorId": "9970650363",
    "encodedId": "OTk3MDY1MDM2Mw",
    "firstName": "VIKRANT",
    "lastName": "BORSE",
    "city": "Nashik",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "HSC",
      "B.Sc",
      "Others",
      "B.Com",
      "BCA",
      "MCA",
      "B.A.",
      "Nursing",
      "Agriculture",
      "M.Sc",
      "M.A.",
      "M.Com",
      "Banking and Finance",
      "Defense Services",
      "ITI",
      "Social Work",
      "UPSC",
      "B.Ed"
    ],
    "languagesKnow": [
      "Hindi",
      "English",
      "Marathi"
    ],
    "experience": 5,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9970650363/1771340618605photo.jpg",
    "organisationName": "VIVEKANAND CAREER ACADEMY",
    "ratePerYear": 3000,
    "plusAmount": 3000,
    "proAmount": 10000,
    "eliteAmount": 50000,
    "bioLength": 1320
  },
  {
    "counsellorId": "9970805934",
    "encodedId": "OTk3MDgwNTkzNA",
    "firstName": "Chanakya",
    "lastName": "Career point",
    "city": "Pune",
    "states": [
      "Maharashtra"
    ],
    "expertise": [
      "Engineering",
      "Medical",
      "Law"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 10,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "",
    "organisationName": "Chanakya Career Point",
    "ratePerYear": 5000,
    "plusAmount": 5000,
    "proAmount": 25000,
    "eliteAmount": 100000,
    "bioLength": 316
  },
  {
    "counsellorId": "9987564702",
    "encodedId": "OTk4NzU2NDcwMg",
    "firstName": "Ajay",
    "lastName": "Bhagat",
    "city": "Nashik, Mumbai Suburb, Vapi, Palghar, Vasai, Surat",
    "states": [
      "Maharashtra",
      "Delhi",
      "Gujarat",
      "Madhya Pradesh",
      "Out of India",
      "Tamil Nadu",
      "Jharkhand",
      "Telangana",
      "Bihar",
      "Rajasthan",
      "Andhra Pradesh",
      "Karnataka",
      "Uttar Pradesh",
      "Chandigarh",
      "Haryana",
      "Dadra and Nagar Haveli and Daman and Diu",
      "Himachal Pradesh",
      "Punjab",
      "Kerala",
      "Goa"
    ],
    "expertise": [
      "Engineering",
      "MBA",
      "HSC",
      "Medical",
      "BBA",
      "Others",
      "BCA",
      "Pharmacy",
      "Diploma in Engineering",
      "MCA",
      "B.A.",
      "Nursing",
      "Journalism and Mass Communication",
      "M.Com",
      "M.A.",
      "Banking and Finance",
      "Cost and Management Accounting",
      "ITI",
      "Social Work",
      "Psychology",
      "Defense Services",
      "B.Ed",
      "Aviation",
      "UPSC",
      "Company Secretary"
    ],
    "languagesKnow": [
      "Hindi",
      "Marathi",
      "English"
    ],
    "experience": 15,
    "rating": 4,
    "numberOfRatings": 0,
    "photoUrl": "https://storage.googleapis.com/procounsellor-71824.firebasestorage.app/counsellors/9987564702/1770548180607photo.jpg",
    "organisationName": "All Out Solution",
    "ratePerYear": 4000,
    "plusAmount": 4000,
    "proAmount": 10000,
    "eliteAmount": 30000,
    "bioLength": 1313
  }
];
